{-# LANGUAGE Strict #-}
-- | ONE canonical seam identity for the chunk init queue, shared by
--   every producer that appends to it or counts it.
--
--   Chunks are STORED u-wrapped, so near the cylindrical seam one
--   PHYSICAL chunk has two coordinate spellings
--   ('World.Chunk.Types.wrapChunkCoordU'). The queue's consumer
--   ('World.Thread.ChunkLoading.drainInitQueues') has always
--   canonicalised before generating and inserting, which is why two
--   aliases never produced two chunks. Its PRODUCERS did not, so the
--   queue itself could hold both spellings of one chunk:
--
--     * @world.loadChunksInRegion@ counted and appended raw, so a
--       second request naming the other alias of an already-queued or
--       already-loaded chunk reported work it was not doing;
--     * the dump path's @--region@ fill reported the same raw count;
--     * fresh world init and saved-page restore seeded the queue with a
--       raw load-radius box that can alias against itself on a small
--       world, and against a later canonical request.
--
--   Nothing was mis-generated by that (issue #43 had already closed the
--   duplicate-generation half), but the counts were fiction: inflated
--   @world.waitForChunks@ remaining, inflated 'LoadPhase2' progress, and
--   alias entries consuming batch slots ahead of real work.
--
--   Every producer now measures and dedups through the functions here,
--   and the consumer canonicalises through the SAME
--   'canonicalChunkCoord' — producers and consumer disagreeing on the
--   identity would put the guarantee back where it started.
--
--   Since #2001 that identity is no longer this module's own. It lives
--   in "World.Chunk.Residency" (re-exported here for the producers that
--   already used it, under its new name), because the camera-driven
--   loader turned out to be running a SECOND canonicalisation beside
--   it — a bare 'World.Chunk.Types.wrapChunkCoordU' with neither guard —
--   and \"is this chunk already known?\" is now a state the page's
--   residency owner names outright rather than something
--   'enqueueChunkRequest' reconstructs.
module World.Chunk.Queue
    ( canonicalChunkCoord
    , dedupChunkQueue
    , newChunkQueueEntries
    , initialChunkQueue
    , seedInitialQueue
    , enqueueChunkRequest
    ) where

import UPrelude
import Data.IORef (readIORef, atomicModifyIORef')
import qualified Data.HashSet as HS
import World.Chunk.Admit (registerChunkDemand)
import World.Chunk.Residency (canonicalChunkCoord)
import World.Chunk.Types (ChunkCoord(..))
import World.Generate.Constants (chunkLoadRadius)
import World.Generate.Types (WorldGenParams(..))
import World.Page.Types (WorldPageId(..))
import World.State.Types (WorldState(..))

-- | Keep one entry per PHYSICAL chunk, preserving the FIRST occurrence
--   and the input order.
--
--   Both halves are load-bearing. 'drainInitQueues' consumes the front
--   @maxChunksPerTick@ entries, so reordering would reorder generation;
--   and it drops a drained batch from the queue BY COORD, so the
--   spelling that survives has to be the one actually in the queue.
--   A list with no aliases therefore comes back exactly as it went in.
dedupChunkQueue ∷ (ChunkCoord → ChunkCoord) → [ChunkCoord] → [ChunkCoord]
dedupChunkQueue canon = go HS.empty
  where
    go _    []       = []
    go seen (c : cs)
        | HS.member key seen = go seen cs
        | otherwise          = c : go (HS.insert key seen) cs
      where key = canon c

-- | The entries a request actually adds: input order, one per physical
--   chunk, dropping every chunk the page already has. The predicate is
--   asked about the CANONICAL key, so an alias of a loaded or pending
--   chunk is recognised as the same work.
newChunkQueueEntries
    ∷ (ChunkCoord → ChunkCoord)   -- ^ 'canonicalChunkCoord' for the page
    → (ChunkCoord → Bool)         -- ^ is this canonical key already loaded or queued?
    → [ChunkCoord]                -- ^ the requested coords, in order
    → [ChunkCoord]
newChunkQueueEntries canon alreadyHave =
    dedupChunkQueue canon . filter (not . alreadyHave . canon)

-- | A page's initial chunk set: the load-radius box around the centre
--   chunk the caller generates synchronously, minus that centre, one
--   entry per physical chunk.
--
--   Returns the queue and the PHYSICAL total for 'LoadPhase2' — the
--   unique chunks in the box, counting the synchronously loaded centre
--   exactly once. On a small world the box aliases against itself (at
--   worldSize 8 the u = ±4 column is one physical column), so the raw
--   @(2r+1)^2@ formula over-counts and the progress bar never reaches
--   its own total.
--
--   Shared by fresh world init and saved-page restore so the two seed
--   the queue identically.
initialChunkQueue
    ∷ (ChunkCoord → ChunkCoord)   -- ^ 'canonicalChunkCoord' for the page
    → ChunkCoord                  -- ^ the centre chunk, already loaded
    → ([ChunkCoord], Int)
initialChunkQueue canon centre = (queue, length queue + 1)
  where
    ChunkCoord ccx ccy = centre
    centreKey = canon centre
    box = [ ChunkCoord cx cy
          | cx ← [ccx - chunkLoadRadius .. ccx + chunkLoadRadius]
          , cy ← [ccy - chunkLoadRadius .. ccy + chunkLoadRadius]
          ]
    queue = newChunkQueueEntries canon (≡ centreKey) box

-- | Append a chunk request to a page's init queue under that page's own
--   canonical identity, returning the number of PHYSICAL chunks queued.
--
--   Used by @world.loadChunksInRegion@ and the dump path's @--region@
--   fill — the two producers that APPEND rather than seed, and so must
--   dedup against what the page already holds.
--
--   Since #2001 the dedup is ONE atomic transition on the page's
--   residency owner ("World.Chunk.Admit"), not a reconstruction from two
--   'IORef's. The owner already knows every canonical key that is
--   resident, requested or in flight, so a coord naming another spelling
--   of any of them is neither counted nor appended. That replaces the
--   snapshot protocol this function used to carry (#43): it had to read
--   'wsInitQueueRef' BEFORE 'wsTilesRef', because the world thread keeps
--   a chunk queued for the whole of its generation and removes it only
--   after inserting, so the opposite order left a window in which an
--   in-flight chunk was visible in neither snapshot and got queued
--   twice. With a single owner value there is no pair of snapshots to
--   order, and \"in flight\" is a state the owner names outright rather
--   than an inference from queue membership.
--
--   The append that follows is still safe against the world thread: this
--   queue has a single appending thread — the Lua thread in a live
--   engine, the dump driver in dump mode (where no script issues region
--   requests) — the drain removes a batch BY COORD so a concurrent
--   append survives it, and the other two producers REPLACE the queue
--   while setting the page up and never race this one.
--
--   A page with no generation params yet queues NOTHING and reports 0:
--   its physical identity is unknown, so no alias could be recognised,
--   and 'drainInitQueues' refuses to drain such a page anyway, which
--   would leave the appended coords stuck in the queue inflating every
--   remaining count that reads it.
enqueueChunkRequest ∷ WorldPageId → WorldState → [ChunkCoord] → IO Int
enqueueChunkRequest pid ws coords = do
    mParams ← readIORef (wsGenParamsRef ws)
    case mParams of
        Nothing → pure 0
        Just params → do
            needed ← registerChunkDemand ws pid params coords
            atomicModifyIORef' (wsInitQueueRef ws) $ \q →
                (q ⧺ needed, length needed)

-- | Seed a page's init queue with its initial box and report the
--   @('LoadPhase2' remaining, total)@ pair that describes it.
--
--   Shared by fresh world init and saved-page restore so the two cannot
--   drift, and it is a REGISTER-then-APPEND, never a write. A page is
--   registered in @wmWorlds@ — and given its generation params — before
--   its box is queued, so a @world.loadChunksInRegion@ accepted in that
--   window has already been counted and registered on the owner;
--   replacing the queue would drop its coords while leaving them
--   requested, deduplicating every later request for them.
--
--   The total is @remaining + 1@: the queue as it now stands, plus the
--   synchronously generated centre, which is the one chunk already
--   resident at this point. With no concurrent request that is exactly
--   the box's own physical total ('initialChunkQueue'\'s second
--   component), which is what 'LoadPhase2' has always progressed
--   towards. Deriving it from the queue rather than from the box is what
--   keeps a retained request from making @remaining@ exceed @total@ —
--   @world.getInitProgress@ reports @total - remaining@ completed, so
--   that would surface as NEGATIVE progress through the public API.
seedInitialQueue ∷ WorldPageId → WorldState → WorldGenParams
                 → [ChunkCoord] → IO (Int, Int)
seedInitialQueue pid ws params boxCoords = do
    needed ← registerChunkDemand ws pid params boxCoords
    remaining ← atomicModifyIORef' (wsInitQueueRef ws) $ \q →
        let q' = q ⧺ needed in (q', length q')
    pure (remaining, remaining + 1)
