{-# LANGUAGE TemplateHaskell #-}
-- | The uniform buffer object's layout, written down exactly once.
--
--   'uboMembers' is the ONE ordered enumeration of the block's members.
--   Everything the render path needs is derived from it:
--
--     * the @UniformBufferObject@ record and its 'Storable' instance,
--       generated by 'declareUniformBufferObject' and spliced into
--       "Engine.Graphics.Vulkan.Types";
--     * the std140 byte offsets, total size and base alignment that
--       instance uses;
--     * the GLSL @UniformBufferObject@ uniform block ('uboGlslBlock'),
--       interpolated into every shader that declares it by
--       "Engine.Graphics.Vulkan.ShaderCode".
--
--   Before #1072 the layout was written out five times — the record, a
--   'Storable' instance carrying literal byte offsets, a comment block
--   restating every one of them, and four GLSL blocks, three of which had
--   already fallen two members behind. That divergence was benign only
--   because it was a stale PREFIX: appending a member is safe, but
--   inserting one in the middle would have shifted every member after it
--   while the short blocks kept reading the old offsets, with no build
--   error and no runtime diagnostic. Adding a member is now one row here;
--   inserting one moves the Haskell side and every shader together.
--
--   This module exists separately for the same reason
--   "Engine.Graphics.Vulkan.Texture.Limits" does: Template Haskell's stage
--   restriction means a value spliced into — or interpolated into — a quote
--   has to be defined in a DIFFERENT module than the quote itself (#975).
module Engine.Graphics.Vulkan.Uniform.Layout
  ( -- * The canonical enumeration
    UBOMemberType(..)
  , UBOMember(..)
  , uboMembers
    -- * Derived std140 layout
  , uboMemberOffsets
  , uboPayloadSize
  , uboBaseAlignment
  , uboStd140Size
    -- * Derived GLSL
  , GlslSource(..)
  , glslTypeName
  , glslArraySuffix
  , uboGlslBlock
    -- * Derived Haskell
  , declareUniformBufferObject
  , peekVec4Array
  , pokeVec4Array
  ) where

import UPrelude
import qualified Data.Vector as V
import Language.Haskell.TH
import Linear (M44, V4(..))
import Engine.Graphics.Solar (maxSolarPages)

-- | The GLSL type of a UBO member.
--
--   Deliberately CLOSED. Every derivation below is a total case over this
--   type, so under @-Wincomplete-patterns -Werror@ a member type nobody has
--   taught the generator about fails the build rather than silently
--   producing a wrong offset. Widening the block therefore starts here.
data UBOMemberType
    = UBOMat4   -- ^ GLSL @mat4@ / Haskell @M44 Float@
    | UBOFloat  -- ^ GLSL @float@ / Haskell @Float@
    | UBOVec4Array !Int
      -- ^ GLSL @vec4 name[n]@ / Haskell @V.Vector (V4 Float)@ of
      --   exactly @n@ elements. std140 gives a @vec4@ array a 16-byte
      --   element stride, which is the natural size of the element
      --   anyway, so the array is dense — unlike a @float[]@, whose
      --   elements would each be padded to 16.
    deriving (Show, Eq)

-- | One member of the uniform block.
data UBOMember = UBOMember
    { umHsName   ∷ String        -- ^ Haskell record field name
    , umGlslName ∷ String        -- ^ GLSL member name (they differ: the
                                 --   Haskell side is @ubo@-prefixed, and a
                                 --   couple of names were never mechanical
                                 --   translations of each other)
    , umType     ∷ UBOMemberType -- ^ member type
    , umDoc      ∷ String        -- ^ what the member is for
    }

-- | The uniform block, in order. THE definition — nothing else in the
--   engine or in any shader may enumerate these members.
--
--   Order is layout: under std140 a member's offset is a function of every
--   member before it, so reordering this list changes the binary layout of
--   the buffer — correctly, and on both sides at once.
--
--   It is also ARGUMENT order. @UBO@ is applied positionally at its three
--   call sites, so moving a row past another of the same type silently
--   swaps what those callers pass, exactly as reordering the record's
--   fields always did. Add at the end; reorder only deliberately.
uboMembers ∷ [UBOMember]
uboMembers =
    [ UBOMember "uboModel" "model" UBOMat4
        "model matrix"
    , UBOMember "uboView" "view" UBOMat4
        "world view matrix"
    , UBOMember "uboProj" "proj" UBOMat4
        "world projection matrix"
    , UBOMember "uboUIView" "uiView" UBOMat4
        "UI view matrix"
    , UBOMember "uboUIProj" "uiProj" UBOMat4
        "UI projection matrix"
    , UBOMember "uboBrightness" "brightness" UBOFloat
        "brightness multiplier"
    , UBOMember "uboScreenW" "screenW" UBOFloat
        "framebuffer width in pixels (clamped to >= 1)"
    , UBOMember "uboScreenH" "screenH" UBOFloat
        "framebuffer height in pixels (clamped to >= 1)"
    , UBOMember "uboPixelSnap" "pixelSnap" UBOFloat
        "1.0 enables vertex pixel snapping, 0.0 disables it"
    , UBOMember "uboSunAngle" "sunAngle" UBOFloat
        "day/night cycle angle (0..1)"
    , UBOMember "uboAmbientLight" "ambientLight" UBOFloat
        "minimum ambient brightness"
    , UBOMember "uboCameraFacing" "cameraFacing" UBOFloat
        "0.0 = south, 1.0 = west, 2.0 = north, 3.0 = east"
    , UBOMember "uboDefaultFaceMapSlot" "defaultFaceMapSlot" UBOFloat
        ("bindless slot of the default face map; the world fragment shader "
         <> "uses it when a tile's own face map handle resolves to slot 0 "
         <> "(unregistered) (#286)")
    , UBOMember "uboWorldCircumference" "worldCircumferenceTiles" UBOFloat
        ("the FALLBACK u-axis (gx-gy) circumference in tiles, used by a "
         <> "vertex that names no world page. The world vertex shader "
         <> "divides a vertex's packed world u by this to get its "
         <> "longitude-local day/night phase offset (#483)")
    , UBOMember "uboSolarPages" "solarPages" (UBOVec4Array maxSolarPages)
        ("per-visible-page solar attribution (#1869): entry n-1 holds the "
         <> "base sun angle in .x and the u-axis circumference in tiles in "
         <> ".y for a vertex whose solarPage attribute is n. A vertex with "
         <> "solarPage 0 uses sunAngle/worldCircumferenceTiles above "
         <> "instead. Slots the frame does not describe are filled with "
         <> "those same fallback values")
    ]

-- Note: 'umDoc' is what keeps the per-member documentation from being lost
-- now that the record is generated — read it here, not at the splice site.

----------------------------------------------------------------
-- std140
----------------------------------------------------------------

-- | Base alignment of a member, per the std140 rules the shaders assume:
--   a @float@ aligns to 4, a @mat4@ is an array of four @vec4@ column
--   vectors and so aligns to 16.
memberBaseAlignment ∷ UBOMemberType → Int
memberBaseAlignment UBOMat4          = 16
memberBaseAlignment UBOFloat         = 4
memberBaseAlignment (UBOVec4Array _) = 16

-- | Size a member consumes, per std140.
memberSize ∷ UBOMemberType → Int
memberSize UBOMat4          = 64
memberSize UBOFloat         = 4
memberSize (UBOVec4Array n) = 16 * n

-- | Round @n@ up to the next multiple of @a@.
alignUp ∷ Int → Int → Int
alignUp n a = ((n + a - 1) `div` a) * a

-- | Byte offset of every member, in 'uboMembers' order.
--
--   As of #1072 these are @0, 64, 128, 192, 256, 320, 324, 328, 332, 336,
--   340, 344, 348, 352@ — unchanged from the hand-written instance this
--   replaced, which is what makes the change representation-preserving.
--   #1869 APPENDED @solarPages@ at 368 (352 + 4, rounded up to the
--   @vec4@ array's 16-byte alignment), leaving every one of those
--   offsets where it was.
uboMemberOffsets ∷ [Int]
uboMemberOffsets = reverse (snd (foldl' step (0 ∷ Int, []) uboMembers))
  where
    step (cursor, acc) m =
        let off = alignUp cursor (memberBaseAlignment (umType m))
        in (off + memberSize (umType m), off : acc)

-- | Bytes actually occupied by members: the end of the last one, with no
--   trailing padding. 496 today (356 through @worldCircumferenceTiles@,
--   then 12 bytes of alignment padding and @solarPages@' 128).
uboPayloadSize ∷ Int
uboPayloadSize = foldl' step 0 uboMembers
  where
    step cursor m =
        alignUp cursor (memberBaseAlignment (umType m)) + memberSize (umType m)

-- | Base alignment of the block: std140 takes the largest member base
--   alignment and rounds it up to a multiple of 16. 16 today, and 16 for
--   any member set — nothing in std140 aligns above @vec4@.
uboBaseAlignment ∷ Int
uboBaseAlignment =
    alignUp (maximum (1 : map (memberBaseAlignment . umType) uboMembers)) 16

-- | Size of the block, which under std140 is 'uboPayloadSize' rounded up to
--   'uboBaseAlignment' — 496 today, which 'uboPayloadSize' already is a
--   multiple of, so there is no trailing padding at present.
--
--   This is what 'sizeOf' reports, so it is what the engine allocates per
--   uniform buffer and what it puts in the descriptor's @range@
--   ("Engine.Graphics.Vulkan.Init"). The padding is never written and never
--   read; the point of paying for it is that @sizeOf@ and @alignment@ now
--   agree, so the type stays correct the day something puts it in an array.
uboStd140Size ∷ Int
uboStd140Size = alignUp uboPayloadSize uboBaseAlignment

----------------------------------------------------------------
-- GLSL
----------------------------------------------------------------

-- | Raw GLSL source text.
--
--   The @glsl@ quasiquoter renders an interpolated @${…}@ through 'show',
--   which is why this is a newtype with a hand-written 'Show' rather than a
--   plain 'String': a 'String' would splice in a Haskell string LITERAL,
--   quotes and @\\n@ escapes and all.
newtype GlslSource = GlslSource String

instance Show GlslSource where
    show (GlslSource s) = s

-- | GLSL spelling of a member type.
glslTypeName ∷ UBOMemberType → String
glslTypeName UBOMat4          = "mat4"
glslTypeName UBOFloat         = "float"
glslTypeName (UBOVec4Array _) = "vec4"

-- | The @[n]@ a member's DECLARATION carries after its name, empty for
--   a scalar\/matrix. Spelled after the name rather than as part of the
--   type so the block reads as ordinary GLSL (@vec4 solarPages[8];@).
glslArraySuffix ∷ UBOMemberType → String
glslArraySuffix UBOMat4          = ""
glslArraySuffix UBOFloat         = ""
glslArraySuffix (UBOVec4Array n) = "[" <> show n <> "]"

-- | The uniform block declaration every shader that reads the UBO
--   interpolates, so none of them can carry a stale member list.
--
--   @std140@ is stated explicitly. It is the default for a @uniform@ block
--   and the shaders relied on that silently before #1072, but the layout
--   derived above IS the std140 one, so the contract belongs in the source.
--
--   Emitted as a SINGLE line on purpose: @glsl@ inserts one @#line@
--   directive at the top of the quote and the docs warn that an
--   interpolated newline throws the numbering off, so a one-line block
--   keeps compile errors in the rest of the shader pointing at the right
--   Haskell line. GLSL does not care about the whitespace.
uboGlslBlock ∷ GlslSource
uboGlslBlock = GlslSource $ mconcat
    [ "layout(set = 0, binding = 0, std140) uniform UniformBufferObject { "
    , mconcat [ glslTypeName (umType m) <> " " <> umGlslName m
                  <> glslArraySuffix (umType m) <> "; "
              | m ← uboMembers ]
    , "} ubo;"
    ]

----------------------------------------------------------------
-- Haskell
----------------------------------------------------------------

-- | Haskell type of a member.
memberHsType ∷ UBOMemberType → Q Type
memberHsType UBOMat4          = [t| M44 Float |]
memberHsType UBOFloat         = [t| Float |]
memberHsType (UBOVec4Array _) = [t| V.Vector (V4 Float) |]

-- | Read a @vec4[n]@ member back. std140 puts element @i@ at
--   @offset + 16 * i@, which is exactly @sizeOf (V4 Float)@, so the
--   array is read densely.
peekVec4Array ∷ Int → Ptr α → Int → IO (V.Vector (V4 Float))
peekVec4Array n ptr off =
    V.generateM n $ \i → peekByteOff ptr (off + 16 * i)

-- | Write a @vec4[n]@ member. Writes EXACTLY @n@ elements whatever the
--   vector's length: a short vector is zero-filled and a long one
--   truncated, so a caller can never write past the member or leave a
--   slot holding the previous frame's value.
pokeVec4Array ∷ Int → Ptr α → Int → V.Vector (V4 Float) → IO ()
pokeVec4Array n ptr off values =
    forM_ [0 .. n - 1] $ \i →
        pokeByteOff ptr (off + 16 * i)
            (fromMaybe (V4 0 0 0 0) (values V.!? i))

-- | An 'Int' literal expression.
intE ∷ Int → Q Exp
intE n = litE (integerL (fromIntegral n))

-- | Generate @data UniformBufferObject = UBO {…}@ and its 'Storable'
--   instance from 'uboMembers'. Spliced by
--   "Engine.Graphics.Vulkan.Types"; run @-ddump-splices@ to read the
--   result.
--
--   The fields are given explicit strictness annotations rather than
--   inheriting them from the splice site's @Strict@ pragma, so the record
--   means the same thing wherever it is spliced.
declareUniformBufferObject ∷ Q [Dec]
declareUniformBufferObject = do
    let tyName  = mkName "UniformBufferObject"
        conName = mkName "UBO"
        recField m = varBangType (mkName (umHsName m))
                       (bangType (bang noSourceUnpackedness sourceStrict)
                                 (memberHsType (umType m)))
    dataDec ← dataD (cxt []) tyName [] Nothing
                    [recC conName (map recField uboMembers)]
                    [derivClause Nothing [conT ''Show]]
    instDec ← instanceD (cxt []) (conT ''Storable `appT` conT tyName)
                    [ sizeOfDec, alignmentDec, peekDec conName, pokeDec conName ]
    pure [dataDec, instDec]

-- | @sizeOf@ / @alignment@ take LAZY (@~@) patterns: "Engine.Graphics.Vulkan.Types"
--   is compiled with @Strict@ and both are routinely called on @undefined@
--   (@sizeOf (undefined ∷ UniformBufferObject)@), so a strict wildcard would
--   force it. Same reasoning, same shape as the hand-written instances in
--   "Engine.Graphics.Vulkan.Types.Vertex".
sizeOfDec ∷ Q Dec
sizeOfDec = funD 'sizeOf
    [clause [tildeP wildP] (normalB (intE uboStd140Size)) []]

-- | See 'sizeOfDec' for the lazy pattern.
alignmentDec ∷ Q Dec
alignmentDec = funD 'alignment
    [clause [tildeP wildP] (normalB (intE uboBaseAlignment)) []]

-- | @peek@ as @Con ⊚ peekByteOff p o₀ \<*\> peekByteOff p o₁ \<*\> …@.
peekDec ∷ Name → Q Dec
peekDec conName = do
    ptr ← newName "ptr"
    let peekAt m off = case umType m of
            UBOVec4Array n → [| peekVec4Array n $(varE ptr) $(intE off) |]
            _              → [| peekByteOff $(varE ptr) $(intE off) |]
    body ← case zip uboMembers uboMemberOffsets of
        []                 → fail "uboMembers is empty: the UBO needs at least one member"
        ((m0, off0):rest)  → foldl' (\acc (m, off) → [| $acc <*> $(peekAt m off) |])
                              [| $(conE conName) ⊚ $(peekAt m0 off0) |]
                              rest
    funD 'peek [clause [varP ptr] (normalB (pure body)) []]

-- | @poke@ as one @pokeByteOff@ per member, at its derived offset.
pokeDec ∷ Name → Q Dec
pokeDec conName = do
    ptr  ← newName "ptr"
    vars ← mapM (newName . umHsName) uboMembers
    let pokeAt m off v = case umType m of
            UBOVec4Array n →
                [| pokeVec4Array n $(varE ptr) $(intE off) $(varE v) |]
            _ → [| pokeByteOff $(varE ptr) $(intE off) $(varE v) |]
        stmts = zipWith3
            (\m v off → noBindS (pokeAt m off v))
            uboMembers vars uboMemberOffsets
    funD 'poke
        [clause [varP ptr, conP conName (map varP vars)] (normalB (doE stmts)) []]
