{-# LANGUAGE Strict #-}
-- | Chunk-level queries and loading: world.getChunkInfo,
--   world.loadChunksInRegion, world.waitForChunks.
module Engine.Scripting.Lua.API.WorldQuery.Chunk
    ( worldGetChunkInfoFn
    , worldLoadChunksInRegionFn
    , worldWaitForChunksFn
    ) where

import UPrelude
import qualified HsLua as Lua
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import qualified Data.Text.Encoding as TE
import Data.IORef (readIORef)
import Control.Concurrent (threadDelay)
import Engine.Core.Capability.WorldSim
    (WorldSimCapability(..))
import Engine.Core.State (chunkTargetWorldFrom)
import World.Types
import World.Chunk.Queue (enqueueChunkRequest)
import Engine.Scripting.Lua.API.WorldQuery.Lookup (getWorldTileData)

-- | world.getChunkInfo(cx, cy) → table with summary
--   Returns: { loaded=true, fluidCounts={ocean=N,lake=N,river=N,lava=N},
--              minSurf=N, maxSurf=N, minTerrSurf=N, maxTerrSurf=N }
worldGetChunkInfoFn ∷ WorldSimCapability → Lua.LuaE Lua.Exception Lua.NumResults
worldGetChunkInfoFn wsc = do
    mCx ← Lua.tointeger 1
    mCy ← Lua.tointeger 2
    case (mCx, mCy) of
        (Just cx', Just cy') → do
            let coord = ChunkCoord (fromIntegral cx') (fromIntegral cy')
            mTd ← Lua.liftIO $ getWorldTileData wsc
            case mTd ⌦ lookupChunk coord of
                Nothing → do
                    Lua.newtable
                    Lua.pushboolean False
                    Lua.setfield (Lua.nth 2) "loaded"
                    return 1
                Just lc → do
                    let surfMap = lcSurfaceMap lc
                        terrMap = lcTerrainSurfaceMap lc
                        fluidMap = lcFluidMap lc
                        -- Count fluids
                        countFluids = V.foldl' (\(!o,!l,!r,!v) mfc →
                            case mfc of
                                Nothing → (o,l,r,v)
                                Just fc → case fcType fc of
                                    Ocean → (o+1,l,r,v)
                                    Lake  → (o,l+1,r,v)
                                    River → (o,l,r+1,v)
                                    Lava  → (o,l,r,v+1)
                            ) (0∷Int,0∷Int,0∷Int,0∷Int) fluidMap
                        (nOcean, nLake, nRiver, nLava) = countFluids
                        minSurf = VU.minimum surfMap
                        maxSurf = VU.maximum surfMap
                        minTerr = VU.minimum terrMap
                        maxTerr = VU.maximum terrMap
                    Lua.newtable
                    Lua.pushboolean True
                    Lua.setfield (Lua.nth 2) "loaded"
                    -- Fluid counts sub-table
                    Lua.newtable
                    Lua.pushinteger (fromIntegral nOcean)
                    Lua.setfield (Lua.nth 2) "ocean"
                    Lua.pushinteger (fromIntegral nLake)
                    Lua.setfield (Lua.nth 2) "lake"
                    Lua.pushinteger (fromIntegral nRiver)
                    Lua.setfield (Lua.nth 2) "river"
                    Lua.pushinteger (fromIntegral nLava)
                    Lua.setfield (Lua.nth 2) "lava"
                    Lua.setfield (Lua.nth 2) "fluidCounts"
                    -- Surface stats
                    Lua.pushinteger (fromIntegral minSurf)
                    Lua.setfield (Lua.nth 2) "minSurf"
                    Lua.pushinteger (fromIntegral maxSurf)
                    Lua.setfield (Lua.nth 2) "maxSurf"
                    Lua.pushinteger (fromIntegral minTerr)
                    Lua.setfield (Lua.nth 2) "minTerrSurf"
                    Lua.pushinteger (fromIntegral maxTerr)
                    Lua.setfield (Lua.nth 2) "maxTerrSurf"
                    return 1
        _ → do
            Lua.pushnil
            return 1

-- | world.loadChunksInRegion(cx1, cy1, cx2, cy2 [, pageId]) → count
--   Queues chunk coordinates in the rectangle [cx1..cx2] × [cy1..cy2]
--   for generation. Chunks are generated by the world thread at
--   ~4 per tick. Use world.waitForChunks() to block until done.
--   Returns the number of PHYSICAL chunks queued: a coord already
--   loaded or already pending under EITHER of its seam spellings is
--   not counted and not appended, and two aliases inside one rectangle
--   count once (#1723). A page with no generation params yet queues
--   nothing and returns 0.
--
--   The PAGE, not just its state: a chunk key is page-qualified
--   (#2001), so the request has to name the page whose residency owner
--   it registers on — and since #2310 it names the page the CALLER's
--   own preceding @world.show@ chose rather than whichever page is
--   still applied. 'Engine.Core.State.resolveChunkTargetWorld' owns
--   that rule and states why; the optional trailing @pageId@ takes the
--   decision away from it entirely, for a caller that knows its target.
--   An explicit page that is not live queues NOTHING and returns 0
--   rather than falling back to another page.
worldLoadChunksInRegionFn ∷ WorldSimCapability → Lua.LuaE Lua.Exception Lua.NumResults
worldLoadChunksInRegionFn wsc = do
    mCx1 ← Lua.tointeger 1
    mCy1 ← Lua.tointeger 2
    mCx2 ← Lua.tointeger 3
    mCy2 ← Lua.tointeger 4
    mPageArg ← optionalPageArg 5
    case (mCx1, mCy1, mCx2, mCy2, mPageArg) of
        (Just cx1', Just cy1', Just cx2', Just cy2', Just pageArg) → do
            let cx1 = fromIntegral cx1' ∷ Int
                cy1 = fromIntegral cy1' ∷ Int
                cx2 = fromIntegral cx2' ∷ Int
                cy2 = fromIntegral cy2' ∷ Int
                coords = [ ChunkCoord x y
                         | x ← [min cx1 cx2 .. max cx1 cx2]
                         , y ← [min cy1 cy2 .. max cy1 cy2]
                         ]
            -- The count is PHYSICAL chunks, not coordinate spellings:
            -- near the seam one chunk has two names, so a region naming
            -- the other alias of an already-loaded or already-pending
            -- chunk queues nothing and reports 0. The identity, the
            -- dedup and the #43 snapshot ordering all live in
            -- 'enqueueChunkRequest', shared with the dump path.
            count ← Lua.liftIO $ do
                mPage ← chunkTargetWorldFrom pageArg (wsWorldManagerRef wsc)
                case mPage of
                    Just (pid, ws) → enqueueChunkRequest pid ws coords
                    Nothing        → pure 0
            Lua.pushinteger (fromIntegral count)
            return 1
        _ → do
            Lua.pushnil
            return 1

-- | world.waitForChunks([timeout_seconds [, pageId]]) → remaining
--   Blocks until the chunk init queue is empty or timeout is reached.
--   Default timeout: 120 seconds. Returns the number of chunks still
--   remaining (0 if all loaded).
--
--   The target page is resolved ONCE, when the wait begins, and every
--   poll then reads that page's own queue (#2310). Re-resolving per
--   poll — what this did before — meant a @WorldShow@ landing mid-wait
--   silently moved the wait onto the incoming page's empty queue and
--   reported completion for work the outgoing page was still doing.
--
--   It deliberately does NOT remember an earlier
--   @world.loadChunksInRegion@: the request-handle API that would need
--   is out of scope (#2310). A caller that must be independent of any
--   intervening selection request passes the same explicit @pageId@ to
--   both verbs, which is exactly what that argument is for.
worldWaitForChunksFn ∷ WorldSimCapability → Lua.LuaE Lua.Exception Lua.NumResults
worldWaitForChunksFn wsc = do
    timeoutArg ← Lua.tointeger 1
    mPageArg ← optionalPageArg 2
    case mPageArg of
        Nothing → do
            Lua.pushnil
            return 1
        Just pageArg → do
            let timeoutSec = case timeoutArg of
                    Just t | t > 0 → fromIntegral t ∷ Int
                    _              → 120
                maxIter = timeoutSec * 4  -- poll at 250ms intervals
            remaining ← Lua.liftIO $ do
                mPage ← chunkTargetWorldFrom pageArg (wsWorldManagerRef wsc)
                case mPage of
                    Nothing      → pure 0
                    Just (_, ws) → waitLoop ws maxIter
            Lua.pushinteger (fromIntegral remaining)
            return 1
  where
    waitLoop ws 0 = remainingOn ws
    waitLoop ws n = do
        r ← remainingOn ws
        if r ≡ 0
            then return 0
            else do
                threadDelay 250000
                waitLoop ws (n - 1)
    remainingOn ws = length ⊚ readIORef (wsInitQueueRef ws)

-- | The optional trailing page-id argument both verbs above accept
--   (#2310), read off the given stack index.
--
--   Three answers, not two: 'Nothing' is a MALFORMED argument (the
--   caller wrote something that is not a page id, and gets the same
--   @nil@ every other bad argument to these verbs gets), @Just Nothing@
--   is ABSENT (resolve the target from the manager), and
--   @Just (Just pid)@ names one page explicitly.
--
--   The type is checked before the conversion, because 'Lua.tostring'
--   COERCES a number: without this, @world.loadChunksInRegion(0,0,1,1,7)@
--   would silently become a request against a page named @"7"@. A
--   well-formed string naming no live page is not malformed — it
--   resolves to no target and the verb reports 0, which is the contract
--   requirement 2 states.
optionalPageArg ∷ Lua.StackIndex
                → Lua.LuaE Lua.Exception (Maybe (Maybe WorldPageId))
optionalPageArg ix = do
    ty ← Lua.ltype ix
    if ty ≡ Lua.TypeNone ∨ ty ≡ Lua.TypeNil
        then pure (Just Nothing)
        else if ty ≢ Lua.TypeString
            then pure Nothing
            else do
                mbs ← Lua.tostring ix
                pure $ case mbs of
                    Just bs → Just (Just (WorldPageId (TE.decodeUtf8Lenient bs)))
                    Nothing → Nothing
