{-# LANGUAGE Strict #-}
-- | Chunk-level queries and loading: world.getChunkInfo,
--   world.loadChunksInRegion, world.waitForChunks.
module Engine.Scripting.Lua.API.WorldQuery.Chunk
    ( worldGetChunkInfoFn
    , worldLoadChunksInRegionFn
    , worldWaitForChunksFn
    ) where

import UPrelude
import qualified HsLua as Lua
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import Data.IORef (readIORef)
import Control.Concurrent (threadDelay)
import Engine.Core.Capability.WorldSim
    (WorldSimCapability(..))
import Engine.Core.State (activeWorldPageFrom, activeWorldStateFrom)
import World.Types
import World.Chunk.Queue (enqueueChunkRequest)
import Engine.Scripting.Lua.API.WorldQuery.Lookup (getWorldTileData)

-- | world.getChunkInfo(cx, cy) → table with summary
--   Returns: { loaded=true, fluidCounts={ocean=N,lake=N,river=N,lava=N},
--              minSurf=N, maxSurf=N, minTerrSurf=N, maxTerrSurf=N }
worldGetChunkInfoFn ∷ WorldSimCapability → Lua.LuaE Lua.Exception Lua.NumResults
worldGetChunkInfoFn wsc = do
    mCx ← Lua.tointeger 1
    mCy ← Lua.tointeger 2
    case (mCx, mCy) of
        (Just cx', Just cy') → do
            let coord = ChunkCoord (fromIntegral cx') (fromIntegral cy')
            mTd ← Lua.liftIO $ getWorldTileData wsc
            case mTd ⌦ lookupChunk coord of
                Nothing → do
                    Lua.newtable
                    Lua.pushboolean False
                    Lua.setfield (Lua.nth 2) "loaded"
                    return 1
                Just lc → do
                    let surfMap = lcSurfaceMap lc
                        terrMap = lcTerrainSurfaceMap lc
                        fluidMap = lcFluidMap lc
                        -- Count fluids
                        countFluids = V.foldl' (\(!o,!l,!r,!v) mfc →
                            case mfc of
                                Nothing → (o,l,r,v)
                                Just fc → case fcType fc of
                                    Ocean → (o+1,l,r,v)
                                    Lake  → (o,l+1,r,v)
                                    River → (o,l,r+1,v)
                                    Lava  → (o,l,r,v+1)
                            ) (0∷Int,0∷Int,0∷Int,0∷Int) fluidMap
                        (nOcean, nLake, nRiver, nLava) = countFluids
                        minSurf = VU.minimum surfMap
                        maxSurf = VU.maximum surfMap
                        minTerr = VU.minimum terrMap
                        maxTerr = VU.maximum terrMap
                    Lua.newtable
                    Lua.pushboolean True
                    Lua.setfield (Lua.nth 2) "loaded"
                    -- Fluid counts sub-table
                    Lua.newtable
                    Lua.pushinteger (fromIntegral nOcean)
                    Lua.setfield (Lua.nth 2) "ocean"
                    Lua.pushinteger (fromIntegral nLake)
                    Lua.setfield (Lua.nth 2) "lake"
                    Lua.pushinteger (fromIntegral nRiver)
                    Lua.setfield (Lua.nth 2) "river"
                    Lua.pushinteger (fromIntegral nLava)
                    Lua.setfield (Lua.nth 2) "lava"
                    Lua.setfield (Lua.nth 2) "fluidCounts"
                    -- Surface stats
                    Lua.pushinteger (fromIntegral minSurf)
                    Lua.setfield (Lua.nth 2) "minSurf"
                    Lua.pushinteger (fromIntegral maxSurf)
                    Lua.setfield (Lua.nth 2) "maxSurf"
                    Lua.pushinteger (fromIntegral minTerr)
                    Lua.setfield (Lua.nth 2) "minTerrSurf"
                    Lua.pushinteger (fromIntegral maxTerr)
                    Lua.setfield (Lua.nth 2) "maxTerrSurf"
                    return 1
        _ → do
            Lua.pushnil
            return 1

-- | world.loadChunksInRegion(cx1, cy1, cx2, cy2) → count
--   Queues chunk coordinates in the rectangle [cx1..cx2] × [cy1..cy2]
--   for generation. Chunks are generated by the world thread at
--   ~4 per tick. Use world.waitForChunks() to block until done.
--   Returns the number of PHYSICAL chunks queued: a coord already
--   loaded or already pending under EITHER of its seam spellings is
--   not counted and not appended, and two aliases inside one rectangle
--   count once (#1723). A page with no generation params yet queues
--   nothing and returns 0.
worldLoadChunksInRegionFn ∷ WorldSimCapability → Lua.LuaE Lua.Exception Lua.NumResults
worldLoadChunksInRegionFn wsc = do
    mCx1 ← Lua.tointeger 1
    mCy1 ← Lua.tointeger 2
    mCx2 ← Lua.tointeger 3
    mCy2 ← Lua.tointeger 4
    case (mCx1, mCy1, mCx2, mCy2) of
        (Just cx1', Just cy1', Just cx2', Just cy2') → do
            let cx1 = fromIntegral cx1' ∷ Int
                cy1 = fromIntegral cy1' ∷ Int
                cx2 = fromIntegral cx2' ∷ Int
                cy2 = fromIntegral cy2' ∷ Int
                coords = [ ChunkCoord x y
                         | x ← [min cx1 cx2 .. max cx1 cx2]
                         , y ← [min cy1 cy2 .. max cy1 cy2]
                         ]
            -- The count is PHYSICAL chunks, not coordinate spellings:
            -- near the seam one chunk has two names, so a region naming
            -- the other alias of an already-loaded or already-pending
            -- chunk queues nothing and reports 0. The identity, the
            -- dedup and the #43 snapshot ordering all live in
            -- 'enqueueChunkRequest', shared with the dump path.
            count ← Lua.liftIO $ do
                -- The PAGE, not just its state: a chunk key is
                -- page-qualified (#2001), so the request has to name the
                -- page whose residency owner it registers on.
                mPage ← activeWorldPageFrom (wsWorldManagerRef wsc)
                case mPage of
                    Just (pid, ws) → enqueueChunkRequest pid ws coords
                    Nothing        → pure 0
            Lua.pushinteger (fromIntegral count)
            return 1
        _ → do
            Lua.pushnil
            return 1

-- | world.waitForChunks(timeout_seconds) → remaining
--   Blocks until the chunk init queue is empty or timeout is reached.
--   Default timeout: 120 seconds. Returns the number of chunks still
--   remaining (0 if all loaded).
worldWaitForChunksFn ∷ WorldSimCapability → Lua.LuaE Lua.Exception Lua.NumResults
worldWaitForChunksFn wsc = do
    timeoutArg ← Lua.tointeger 1
    let timeoutSec = case timeoutArg of
            Just t | t > 0 → fromIntegral t ∷ Int
            _              → 120
        maxIter = timeoutSec * 4  -- poll at 250ms intervals
    remaining ← Lua.liftIO $ waitLoop maxIter
    Lua.pushinteger (fromIntegral remaining)
    return 1
  where
    waitLoop 0 = checkRemaining
    waitLoop n = do
        r ← checkRemaining
        if r ≡ 0
            then return 0
            else do
                threadDelay 250000
                waitLoop (n - 1)
    checkRemaining = do
        mWs ← activeWorldStateFrom (wsWorldManagerRef wsc)
        case mWs of
            Just ws → length <$> readIORef (wsInitQueueRef ws)
            Nothing → pure 0
