-- | #2655: a randbox paints its stored value and caret inside the input
--   box, not across the dice button. Create World is booted at the formal
--   800x600 minimum and at 1920x1080 because that is where the overflow
--   was observed; the widget fix itself is in scripts/ui/randbox.lua.
--
--   Headless font measurement is zero, so this spec installs a
--   deterministic advance (one font-pixel per Unicode code point, and an
--   error on invalid UTF-8) before the menu builds. At a 24px font that
--   is 24px per code point: an eight-digit seed is 192px, wider than the
--   unscaled seed field's padded interior (200 - 2*8), while one code
--   point still fits. The same ratio holds when Create World's compact
--   fallback shrinks the field, because the field and the font share one
--   scale and the name field is shrunk further to fit its row.
module Test.Headless.UI.RandboxContainment (spec) where

import UPrelude
import Test.Hspec
import Data.Aeson (FromJSON(..), withObject, (.:))
import qualified Data.Text as T
import Test.Headless.UI.ResponsiveMenus.Fixture
    ( withMenusEngine, luaLines, newBareLuaBackend, evalJSON, decodeProbe )

spec ∷ Spec
spec = around withMenusEngine $
    describe "rendered value and caret stay inside the input" $
        forM_ [(800 ∷ Int, 600 ∷ Int), (1920, 1080)] $ \(w, h) →
            it ("at " ++ show w ++ "x" ++ show h) $ \env → do
                ls ← newBareLuaBackend env
                r ← evalJSON ls (probe w h)
                report ← decodeProbe "randbox containment" r
                reportReason report `shouldBe` ""

newtype Report = Report { reportReason ∷ Text }

instance FromJSON Report where
    parseJSON = withObject "randbox containment" $ \o →
        Report <$> o .: "reason"

-- | Same boot the responsive-menu suite uses: randbox/textbox/dropdown
--   init is normally ui_manager_boot's job, and skipping it makes
--   UI.newBox return no handle.
bootCreateWorld ∷ Int → Int → Text
bootCreateWorld w h = luaLines
    [ "require('scripts.ui.randbox').init();"
    , "require('scripts.ui.textbox').init();"
    , "require('scripts.ui.dropdown').init();"
    , "local m = require('scripts.create_world_menu');"
    , "m.init(1,2,3," <> tshow w <> "," <> tshow h <> ");"
    ]

probe ∷ Int → Int → Text
probe w h = T.unlines
    [ "local sizeByText = {}"
    , "engine.getTextWidth = function(_, text, size)"
    , "  if type(text) ~= 'string' then text = '' end"
    , "  local n, bad = utf8.len(text)"
    , "  if not n then error('invalid UTF-8 measured at byte ' .. tostring(bad)) end"
    , "  local px = tonumber(size) or 0"
    , "  if text ~= '' and px > 0 then sizeByText[text] = px end"
    , "  return n * px"
    , "end"
    , bootCreateWorld w h
    , "UI.showPage(m.page);"
    , "local utf8Safe = require('scripts.ui.utf8_safe')"
    , "local randbox = require('scripts.ui.randbox')"
    , "local st = require('scripts.create_world.settings_tab')"
    , "local function elem(name)"
    , "  for _, e in ipairs(UI.getVisibleElements()) do"
    , "    if e.name == name then return e end"
    , "  end"
    , "  return nil"
    , "end"
    , "local function fail(msg) return { reason = msg } end"
    , "local function field(id, textName)"
    , "  local box = UI.getElementInfo(randbox.getElementHandle(id))"
    , "  local btn = UI.getElementInfo(randbox.getBtnHandle(id))"
    , "  local textEl = elem(textName)"
    , "  if not box or not btn or not textEl then return nil end"
    , "  return {"
    , "    full = randbox.getValue(id),"
    , "    input = UI.getTextInput(randbox.getElementHandle(id)) or '',"
    , "    shown = textEl.text or '',"
    , "    textX = textEl.x, boxX = box.x, btnX = btn.x,"
    , "    btnW = btn.width, btnH = btn.height,"
    , "  }"
    , "end"
    , "local seedSnap = field(st.seedRandBoxId, 'world_seed_text')"
    , "if not seedSnap then return fail('seed elements missing after boot') end"
    , "local fontSize = sizeByText[seedSnap.full]"
    , "if not fontSize then"
    , "  randbox.setCursor(st.seedRandBoxId, randbox.getCursor(st.seedRandBoxId))"
    , "  fontSize = sizeByText[seedSnap.full]"
    , "end"
    , "if not fontSize then return fail('seed was never measured') end"
    , "local pad = seedSnap.textX - seedSnap.boxX"
    , "if pad <= 0 then return fail('text padding was ' .. tostring(pad)) end"
    , "local function widthOf(text)"
    , "  return engine.getTextWidth(nil, text, fontSize)"
    , "end"
    , "local function interior(id)"
    , "  local box = UI.getElementInfo(randbox.getElementHandle(id))"
    , "  local btn = UI.getElementInfo(randbox.getBtnHandle(id))"
    , "  local inputW = btn.x - box.x"
    , "  return inputW, inputW - 2 * pad, box, btn"
    , "end"
    , "local function contained(id, textName, wantCaret)"
    , "  local snap = field(id, textName)"
    , "  if not snap then return false, 'missing elements' end"
    , "  local _, _, box, btn = interior(id)"
    , "  local shownW = widthOf(snap.shown)"
    , "  local limit = btn.x - pad"
    , "  if snap.textX + shownW > limit + 0.01 then"
    , "    return false, 'text right ' .. tostring(snap.textX + shownW) .. ' > ' .. tostring(limit)"
    , "  end"
    , "  if snap.textX < box.x - 0.01 then return false, 'text left of the input' end"
    , "  if utf8.len(snap.shown) == nil then return false, 'shown text is invalid UTF-8' end"
    , "  if snap.input ~= snap.full then return false, 'getTextInput differs from getValue' end"
    , "  if wantCaret then"
    , "    local caret = elem(textName:gsub('_text$', '_cursor'))"
    , "    if not caret then return false, 'missing caret' end"
    , "    local caretW = widthOf('|')"
    , "    if caret.x < box.x - 0.01 then"
    , "      return false, 'caret left ' .. tostring(caret.x) .. ' < ' .. tostring(box.x)"
    , "    end"
    , "    if caret.x + caretW > btn.x + 0.01 then"
    , "      return false, 'caret right ' .. tostring(caret.x + caretW) .. ' > ' .. tostring(btn.x)"
    , "    end"
    , "  end"
    , "  return true, ''"
    , "end"
    , "local function cursorInShown(full, shown, cursor)"
    , "  local n = utf8Safe.codepointLength(full)"
    , "  local m = utf8Safe.codepointLength(shown)"
    , "  for startCp = 0, n do"
    , "    if utf8Safe.slice(full, startCp, startCp + m) == shown"
    , "       and cursor >= startCp and cursor <= startCp + m then"
    , "      return true"
    , "    end"
    , "  end"
    , "  return false"
    , "end"
    , "local seedInputW, seedAvail = interior(st.seedRandBoxId)"
    , "local seedFullW = widthOf(seedSnap.full)"
    , "if utf8.len(seedSnap.full) ~= 8 then"
    , "  return fail('initial seed length ' .. tostring(utf8.len(seedSnap.full)))"
    , "end"
    , "if seedFullW <= seedAvail then"
    , "  return fail('initial seed does not overflow: full=' .. tostring(seedFullW)"
    , "    .. ' avail=' .. tostring(seedAvail) .. ' pad=' .. tostring(pad)"
    , "    .. ' input=' .. tostring(seedInputW) .. ' font=' .. tostring(fontSize))"
    , "end"
    , "if seedSnap.shown == '' or seedSnap.shown == seedSnap.full"
    , "   or seedSnap.full:sub(-#seedSnap.shown) ~= seedSnap.shown then"
    , "  return fail('initial seed display is not a clipped suffix: shown length '"
    , "    .. tostring(utf8.len(seedSnap.shown)))"
    , "end"
    , "do"
    , "  local ok, why = contained(st.seedRandBoxId, 'world_seed_text', false)"
    , "  if not ok then return fail('initial seed ' .. why) end"
    , "end"
    , "do"
    , "  local nameSnap = field(st.nameRandBoxId, 'world_name_text')"
    , "  if not nameSnap then return fail('name elements missing after boot') end"
    , "  local ok, why = contained(st.nameRandBoxId, 'world_name_text', false)"
    , "  if not ok then return fail('initial name ' .. why) end"
    , "  if math.abs((nameSnap.textX - nameSnap.boxX) - pad) > 0.01 then"
    , "    return fail('initial name did not sit on the text padding')"
    , "  end"
    , "end"
    , "local nameBtn = UI.getElementInfo(randbox.getBtnHandle(st.nameRandBoxId))"
    , "randbox.randomize(st.seedRandBoxId)"
    , "local rolled = randbox.getValue(st.seedRandBoxId)"
    , "if utf8.len(rolled) ~= 8 or not rolled:match('^[0-9A-F]+$') then"
    , "  return fail('randomized seed is not 8 hex digits')"
    , "end"
    , "if UI.getTextInput(randbox.getElementHandle(st.seedRandBoxId)) ~= rolled then"
    , "  return fail('randomized seed getTextInput drifted')"
    , "end"
    , "do"
    , "  local _, avail = interior(st.seedRandBoxId)"
    , "  if widthOf(rolled) <= avail then return fail('randomized seed does not overflow') end"
    , "  local snap = field(st.seedRandBoxId, 'world_seed_text')"
    , "  if not snap or snap.shown == '' or snap.shown == rolled"
    , "     or rolled:sub(-#snap.shown) ~= snap.shown then"
    , "    return fail('randomized seed display is not a clipped suffix')"
    , "  end"
    , "  local ok, why = contained(st.seedRandBoxId, 'world_seed_text', false)"
    , "  if not ok then return fail('randomized seed ' .. why) end"
    , "end"
    , "local okRep, repertoire = pcall(world.generatedNameCharacters)"
    , "if not okRep or type(repertoire) ~= 'string' then"
    , "  return fail('world.generatedNameCharacters unavailable')"
    , "end"
    , "local multi = {}"
    , "for _, cp in utf8.codes(repertoire) do"
    , "  local ch = utf8.char(cp)"
    , "  if #ch > 1 then multi[#multi + 1] = ch end"
    , "  if #multi >= 20 then break end"
    , "end"
    , "if #multi < 20 then return fail('repertoire has ' .. tostring(#multi) .. ' multibyte chars') end"
    , "local longName = table.concat(multi)"
    , "local nameId = st.nameRandBoxId"
    , "randbox.setValue(nameId, longName)"
    , "if randbox.getValue(nameId) ~= longName"
    , "   or UI.getTextInput(randbox.getElementHandle(nameId)) ~= longName then"
    , "  return fail('setValue did not keep the complete name')"
    , "end"
    , "do"
    , "  local inputW, avail = interior(nameId)"
    , "  local fullW = widthOf(longName)"
    , "  if fullW <= avail then"
    , "    return fail('long name does not overflow: full=' .. tostring(fullW)"
    , "      .. ' avail=' .. tostring(avail) .. ' input=' .. tostring(inputW))"
    , "  end"
    , "  if widthOf(multi[1]) > avail then return fail('one code point does not fit the name field') end"
    , "  local snap = field(nameId, 'world_name_text')"
    , "  if not snap or utf8.len(snap.shown) == 0 or utf8.len(snap.shown) >= utf8.len(longName)"
    , "     or longName:sub(-#snap.shown) ~= snap.shown then"
    , "    return fail('setValue display is not a clipped suffix')"
    , "  end"
    , "  if math.abs((snap.textX - snap.boxX) - pad) > 0.01 then"
    , "    return fail('unfocused name text left the padding')"
    , "  end"
    , "  local ok, why = contained(nameId, 'world_name_text', false)"
    , "  if not ok then return fail('setValue ' .. why) end"
    , "end"
    , "randbox.focus(nameId)"
    , "do"
    , "  local snap = field(nameId, 'world_name_text')"
    , "  if not snap or longName:sub(-#snap.shown) ~= snap.shown then"
    , "    return fail('focused end display is not a suffix')"
    , "  end"
    , "  if randbox.getCursor(nameId) ~= utf8.len(longName) then"
    , "    return fail('focus did not place the cursor at the end')"
    , "  end"
    , "  if not cursorInShown(longName, snap.shown, randbox.getCursor(nameId)) then"
    , "    return fail('focused caret is outside the shown suffix')"
    , "  end"
    , "  local ok, why = contained(nameId, 'world_name_text', true)"
    , "  if not ok then return fail('focused end ' .. why) end"
    , "end"
    , "local endShown = elem('world_name_text').text"
    , "local steps = 0"
    , "while randbox.getCursor(nameId) > 0 do"
    , "  steps = steps + 1"
    , "  if steps > 40 then return fail('left walk did not reach the start') end"
    , "  randbox.onCursorLeft()"
    , "  local snap = field(nameId, 'world_name_text')"
    , "  if not snap or snap.shown == ''"
    , "     or not cursorInShown(longName, snap.shown, randbox.getCursor(nameId)) then"
    , "    return fail('left step ' .. tostring(steps) .. ' hid the cursor')"
    , "  end"
    , "  local ok, why = contained(nameId, 'world_name_text', true)"
    , "  if not ok then return fail('left step ' .. tostring(steps) .. ' ' .. why) end"
    , "end"
    , "do"
    , "  local snap = field(nameId, 'world_name_text')"
    , "  if not snap or longName:sub(1, #snap.shown) ~= snap.shown or snap.shown == endShown then"
    , "    return fail('left walk did not reveal the clipped head')"
    , "  end"
    , "end"
    , "randbox.onCursorRight()"
    , "if randbox.getCursor(nameId) ~= 1 then return fail('cursor right did not advance one code point') end"
    , "do"
    , "  local snap = field(nameId, 'world_name_text')"
    , "  if not snap or longName:sub(1, #snap.shown) ~= snap.shown"
    , "     or not cursorInShown(longName, snap.shown, 1) then"
    , "    return fail('cursor right left the revealed head')"
    , "  end"
    , "  local ok, why = contained(nameId, 'world_name_text', true)"
    , "  if not ok then return fail('cursor right ' .. why) end"
    , "end"
    , "randbox.onEnd()"
    , "do"
    , "  local snap = field(nameId, 'world_name_text')"
    , "  if randbox.getCursor(nameId) ~= utf8.len(longName)"
    , "     or not snap or longName:sub(-#snap.shown) ~= snap.shown then"
    , "    return fail('End did not return to a suffix')"
    , "  end"
    , "  local ok, why = contained(nameId, 'world_name_text', true)"
    , "  if not ok then return fail('end ' .. why) end"
    , "end"
    , "randbox.onHome()"
    , "randbox.onCursorRight()"
    , "randbox.onCharInput(multi[1])"
    , "local expected = utf8Safe.slice(longName, 0, 1) .. multi[1] .. utf8Safe.slice(longName, 1)"
    , "if randbox.getValue(nameId) ~= expected"
    , "   or UI.getTextInput(randbox.getElementHandle(nameId)) ~= expected then"
    , "  return fail('multibyte insert did not keep the complete value')"
    , "end"
    , "if utf8.len(expected) ~= 21 or randbox.getCursor(nameId) ~= 2 then"
    , "  return fail('multibyte insert cursor/length')"
    , "end"
    , "do"
    , "  local snap = field(nameId, 'world_name_text')"
    , "  if not snap or snap.shown == ''"
    , "     or not cursorInShown(expected, snap.shown, randbox.getCursor(nameId)) then"
    , "    return fail('insert hid the cursor')"
    , "  end"
    , "  local ok, why = contained(nameId, 'world_name_text', true)"
    , "  if not ok then return fail('insert ' .. why) end"
    , "end"
    , "local btnNow = UI.getElementInfo(randbox.getBtnHandle(nameId))"
    , "if math.abs(btnNow.x - nameBtn.x) > 0.01"
    , "   or math.abs(btnNow.width - nameBtn.width) > 0.01"
    , "   or math.abs(btnNow.height - nameBtn.height) > 0.01 then"
    , "  return fail('dice button geometry changed during editing')"
    , "end"
    , "randbox.onHome()"
    , "randbox.onCursorRight()"
    , "local valueBefore = randbox.getValue(nameId)"
    , "local cursorBefore = randbox.getCursor(nameId)"
    , "m.onFramebufferResize(" <> tshow w <> ", " <> tshow h <> ")"
    , "nameId = st.nameRandBoxId"
    , "if randbox.getValue(nameId) ~= valueBefore then return fail('resize dropped the name') end"
    , "if randbox.getCursor(nameId) ~= cursorBefore or cursorBefore ~= 1 then"
    , "  return fail('resize did not restore the prefix cursor')"
    , "end"
    , "if not randbox.isFocused(nameId) then return fail('resize dropped focus') end"
    , "if UI.getTextInput(randbox.getElementHandle(nameId)) ~= valueBefore then"
    , "  return fail('resize getTextInput drifted')"
    , "end"
    , "do"
    , "  local snap = field(nameId, 'world_name_text')"
    , "  if not snap or valueBefore:sub(1, #snap.shown) ~= snap.shown or snap.shown == ''"
    , "     or not cursorInShown(valueBefore, snap.shown, cursorBefore) then"
    , "    return fail('resize did not keep the cursor inside a revealed head')"
    , "  end"
    , "  local ok, why = contained(nameId, 'world_name_text', true)"
    , "  if not ok then return fail('resize ' .. why) end"
    , "end"
    , "return { reason = '' }"
    ]
