module World.Texture.Types where

import UPrelude

data WorldTextureType
    = GraniteTexture
    | DioriteTexture
    | GabbroTexture
    | NoTexture
    | OceanTexture
    | IsoFaceMap
    | SlopeFaceMapN
    | SlopeFaceMapE
    | SlopeFaceMapNE
    | SlopeFaceMapS
    | SlopeFaceMapNS
    | SlopeFaceMapES
    | SlopeFaceMapNES
    | SlopeFaceMapW
    | SlopeFaceMapNW
    | SlopeFaceMapEW
    | SlopeFaceMapNEW
    | SlopeFaceMapSW
    | SlopeFaceMapNSW
    | SlopeFaceMapESW
    | SlopeFaceMapNESW
    | NoFaceMap
    | ZoomGraniteTexture
    | ZoomDioriteTexture
    | ZoomGabbroTexture
    | ZoomOceanTexture
    | GlacierTexture
    | LavaTexture
    | ZoomGlacierTexture
    | ZoomLavaTexture
    | BlankTexture
    | BgGraniteTexture
    | BgGabbroTexture
    | BgDioriteTexture
    | BgOceanTexture
    | BgGlacierTexture
    | BgLavaTexture
    | BasaltTexture
    | ObsidianTexture
    | SandstoneTexture
    | LimestoneTexture
    | ShaleTexture
    | ImpactiteTexture
    | IronTexture
    | OlivineTexture
    | PyroxeneTexture
    | FeldsparTexture
    | ZoomBasaltTexture
    | ZoomObsidianTexture
    | ZoomImpactiteTexture
    | BgBasaltTexture
    | BgImpactiteTexture
    | BgObsidianTexture
    | ZoomSandstoneTexture
    | ZoomLimestoneTexture
    | ZoomShaleTexture
    | ZoomIronTexture
    | ZoomOlivineTexture
    | ZoomPyroxeneTexture
    | ZoomFeldsparTexture
    | BgSandstoneTexture
    | BgLimestoneTexture
    | BgShaleTexture
    | BgIronTexture
    | BgOlivineTexture
    | BgPyroxeneTexture
    | BgFeldsparTexture
    deriving (Show, Eq)
