video:
  brightness: 100
  frame_limit: null
  msaa: 1
  pixel_snap: false
  resolution:
    height: 1080
    width: 1920
  texture_filter: nearest
  tooltip_dwell_ms: 400
  ui_scale: 1.5
  vsync: true
  window_mode: windowed
