module Engine.Scripting.Lua.API.Register.Unit
  ( registerUnitAPI
  ) where

import Engine.Scripting.Lua.API.Internal (registerLuaFunction)
import Engine.Scripting.Lua.API.Units
-- The #1000 transfer contract is imported directly rather than through
-- the Units facade: that facade's export list is deliberately frozen at
-- the pre-split surface (see its header).
import Engine.Scripting.Lua.API.Units.Transfer
-- Durable transfer ORDERS (#1247) — the walk-then-commit executor's
-- own verbs, kept in their own module beside the contract they drive.
import Engine.Scripting.Lua.API.Units.TransferOrder
-- #2297's two read-only medical queries, imported directly for the
-- same reason as the transfer verbs above: the Units facade's export
-- list is frozen at the pre-split surface.
import Engine.Scripting.Lua.API.Units.Medical
    (unitCanTreatFn, unitTreatmentRangeFn)
import Engine.Core.State (EngineEnv)
import qualified HsLua as Lua

-- | Populate and install the @unit@ global table.
registerUnitAPI ∷ EngineEnv → Lua.LuaE Lua.Exception ()
registerUnitAPI env = do
  Lua.newtable

  registerLuaFunction "spawn"       (unitSpawnFn env)
  registerLuaFunction "destroy"     (unitDestroyFn env)
  registerLuaFunction "setPos"      (unitSetPosFn env)
  registerLuaFunction "getPos"      (unitGetPosFn env)
  registerLuaFunction "getInfo"     (unitGetInfoFn env)
  registerLuaFunction "list"        (unitListFn env)
  registerLuaFunction "listDefs"    (unitListDefsFn env)
  registerLuaFunction "listAnimations" (unitListAnimationsFn env)
  registerLuaFunction "moveTo"      (unitMoveToFn env)
  registerLuaFunction "setMoveSpeed" (unitSetMoveSpeedFn env)
  registerLuaFunction "jump"        (unitJumpFn env)
  registerLuaFunction "stop"        (unitStopFn env)
  registerLuaFunction "select"      (unitSelectFn env)
  registerLuaFunction "deselectAll" (unitDeselectAllFn env)
  registerLuaFunction "getSelected" (unitGetSelectedFn env)
  registerLuaFunction "isSelected"  (unitIsSelectedFn env)
  registerLuaFunction "hitTestAt"   (unitHitTestAtFn env)
  registerLuaFunction "hitTestInRect" (unitHitTestInRectFn env)
  registerLuaFunction "setSelection" (unitSetSelectionFn env)
  registerLuaFunction "setAnim"     (unitSetAnimFn env)
  registerLuaFunction "setAnimOverride"   (unitSetAnimOverrideFn env)
  registerLuaFunction "clearAnimOverride" (unitClearAnimOverrideFn env)
  registerLuaFunction "setFacing"   (unitSetFacingFn env)
  registerLuaFunction "setFrozen"   (unitSetFrozenFn env)
  registerLuaFunction "setForceLoop" (unitSetForceLoopFn env)
  registerLuaFunction "collapse"    (unitCollapseFn env)
  registerLuaFunction "crawl"       (unitCrawlFn env)
  registerLuaFunction "revive"      (unitReviveFn env)
  registerLuaFunction "kill"        (unitKillFn env)
  registerLuaFunction "recomputeBody" (unitRecomputeBodyFn env)
  registerLuaFunction "getStat"     (unitGetStatFn env)
  registerLuaFunction "getStatBase" (unitGetStatBaseFn env)
  registerLuaFunction "setStat"     (unitSetStatFn env)
  registerLuaFunction "getAllStats" (unitGetAllStatsFn env)
  registerLuaFunction "getInventory" (unitGetInventoryFn env)
  registerLuaFunction "getItemContents" (unitGetItemContentsFn env)
  registerLuaFunction "treatBleeding" (unitTreatBleedingFn env)
  registerLuaFunction "treatInfection" (unitTreatInfectionFn env)
  registerLuaFunction "treatmentRange" (unitTreatmentRangeFn env)
  registerLuaFunction "canTreat" (unitCanTreatFn env)
  registerLuaFunction "frostbite"    (unitFrostbiteFn env)
  registerLuaFunction "injure"       (unitInjureFn env)
  registerLuaFunction "drink"        (unitDrinkFn env)
  registerLuaFunction "eat"          (unitEatFn env)
  registerLuaFunction "feed"         (unitFeedFn env)
  registerLuaFunction "getCalories"  (unitGetCaloriesFn env)
  registerLuaFunction "pickup"       (unitPickupFn env)
  registerLuaFunction "removeItem"   (unitRemoveItemFn env)
  registerLuaFunction "transferItemToBuilding" (unitTransferItemToBuildingFn env)
  registerLuaFunction "transferItemToUnit"     (unitTransferItemToUnitFn env)
  registerLuaFunction "depositToCargo"     (unitDepositToCargoFn env)
  registerLuaFunction "withdrawFromCargo"  (unitWithdrawFromCargoFn env)
  registerLuaFunction "getCarryingWeight"  (unitGetCarryingWeightFn env)
  registerLuaFunction "checkTransfer"      (unitCheckTransferFn env)
  registerLuaFunction "commitTransfer"     (unitCommitTransferFn env)
  registerLuaFunction "transferContract"   (unitTransferContractFn env)
  registerLuaFunction "transferEndpointInfo" (unitTransferEndpointInfoFn env)
  registerLuaFunction "createTransferOrder"  (unitCreateTransferOrderFn env)
  registerLuaFunction "getTransferOrders"    (unitGetTransferOrdersFn env)
  registerLuaFunction "advanceTransferOrder" (unitAdvanceTransferOrderFn env)
  registerLuaFunction "commitTransferOrder"  (unitCommitTransferOrderFn env)
  registerLuaFunction "failTransferOrder"    (unitFailTransferOrderFn env)
  registerLuaFunction "cancelTransferOrder"  (unitCancelTransferOrderFn env)
  registerLuaFunction "pruneTransferOrder"   (unitPruneTransferOrderFn env)
  registerLuaFunction "transitionTo" (unitTransitionToFn env)
  registerLuaFunction "getPose"      (unitGetPoseFn env)
  registerLuaFunction "getFaction"   (unitGetFactionFn env)
  registerLuaFunction "exists"       (unitExistsFn env)
  registerLuaFunction "getAttackRange" (unitGetAttackRangeFn env)
  registerLuaFunction "getAttackCooldown" (unitGetAttackCooldownFn env)
  registerLuaFunction "getAnimDuration" (unitGetAnimDurationFn env)
  registerLuaFunction "getMaxSpeed"  (unitGetMaxSpeedFn env)
  registerLuaFunction "getEquippedWeaponWeight"
                                          (unitGetEquippedWeaponWeightFn env)
  registerLuaFunction "getWeaponWieldedFrom"
                                          (unitGetWeaponWieldedFromFn env)
  registerLuaFunction "getWoundSeverityOn"
                                          (unitGetWoundSeverityOnFn env)
  registerLuaFunction "getWounds"    (unitGetWoundsFn env)
  registerLuaFunction "getScars"     (unitGetScarsFn env)
  registerLuaFunction "getImmunities" (unitGetImmunitiesFn env)
  registerLuaFunction "getInsulation" (unitGetInsulationFn env)
  registerLuaFunction "dropEquipmentToGround" (unitDropEquipmentToGroundFn env)
  registerLuaFunction "dropItemToGround" (unitDropItemToGroundFn env)
  registerLuaFunction "dropItemById"     (unitDropItemByIdFn env)
  registerLuaFunction "getBlood"     (unitGetBloodFn env)
  registerLuaFunction "getPain"      (unitGetPainFn env)
  registerLuaFunction "getMentalEffectiveness" (unitGetMentalEffectivenessFn env)
  registerLuaFunction "getLastAttacker" (unitGetLastAttackerFn env)
  registerLuaFunction "getWeaponClass"  (unitGetWeaponClassFn env)
  registerLuaFunction "modifyItemFill" (unitModifyItemFillFn env)
  registerLuaFunction "modifyItemFillById" (unitModifyItemFillByIdFn env)
  registerLuaFunction "repairItem"     (unitRepairItemFn env)
  registerLuaFunction "addItem"        (unitAddItemFn env)
  registerLuaFunction "getItemTemp"    (unitGetItemTempFn env)
  registerLuaFunction "setItemTemp"    (unitSetItemTempFn env)
  registerLuaFunction "getVisibleTiles" (unitGetVisibleTilesFn env)
  registerLuaFunction "getFrameTexture" (unitGetFrameTextureFn env)
  registerLuaFunction "getFrameSample" (unitGetFrameSampleFn env)
  registerLuaFunction "getPortraitTexture" (unitGetPortraitTextureFn env)
  registerLuaFunction "addModifier"    (unitAddModifierFn env)
  registerLuaFunction "removeModifier" (unitRemoveModifierFn env)
  registerLuaFunction "getModifiers"   (unitGetModifiersFn env)
  registerLuaFunction "clearModifiers" (unitClearModifiersFn env)
  registerLuaFunction "getAllIds"   (unitGetAllIdsFn env)
  registerLuaFunction "getActivity" (unitGetActivityFn env)
  registerLuaFunction "getCurrentAnim" (unitGetCurrentAnimFn env)
  registerLuaFunction "getJumpReach" (unitGetJumpReachFn env)
  registerLuaFunction "lungeImpactSpeed" (unitLungeImpactSpeedFn env)
  registerLuaFunction "getSkill"     (unitGetSkillFn env)
  registerLuaFunction "setSkill"     (unitSetSkillFn env)
  registerLuaFunction "getKnowledge"     (unitGetKnowledgeFn env)
  registerLuaFunction "setKnowledge"     (unitSetKnowledgeFn env)
  registerLuaFunction "getKnowledgeList" (unitGetKnowledgeListFn env)
  registerLuaFunction "addXP"        (unitAddXPFn env)
  registerLuaFunction "getAllSkills" (unitGetAllSkillsFn env)

  Lua.setglobal (Lua.Name "unit")
