-- | Ruin occupant survival (#2754).
--
--   A ruin_small occupant is a persistent encounter member (#916) whose
--   death clears the encounter. Its survival physiology used to run like
--   an acolyte's with nothing to sustain it, so an unvisited occupant on
--   the reported seed-14 world went delirious from hyponatremia and died
--   of electrolyte imbalance — clearing an encounter nobody fought. Enemy
--   definitions are now exempt from survival physiology
--   (@scripts\/unit_survival_exempt.lua@); this group proves the
--   exemption holds in the reported world, and the nested "survival
--   exemption" group ("Test.Headless.Unit.SurvivalExemption") pins its
--   edges unit by unit.
--
--   On the pre-fix physiology this same fixture fails the way the report
--   did: the occupant is delirious (salt_conc about 0.54, the salt
--   imbalance meter filling) roughly 700 to 1,000 engine seconds after
--   its creation, in both the early and the late case.
--
--   __What is real here.__ The world is the #2640 gate's own: seed 14,
--   size 64, 3 plates, page @expedition@, identity @First Expedition@,
--   generated by the real world thread with the shipped content
--   registries loaded. Ruin instance 4 is the reported occupied ruin.
--   Its occupants are created by the production location-stamp hook
--   (@scripts\/location_stamper.lua@), which rolls the roster, calls
--   @unit.spawn@ and registers every occupant on the placed instance;
--   the spawn command then runs through the real unit tick. Nothing
--   else is on the page and nothing wounds the occupants: the run is
--   unfought, which the observer checks.
--
--   __How time moves.__ The bound is simulation time, so it is stepped
--   rather than waited for. Every step advances a scripted clock by
--   'stepDt' and runs, in production order, the real unit tick
--   ('Unit.Thread.unitTickWith': commands, the engine clock, movement,
--   publication), then the real @unit_resources.update@ (physiology)
--   and @unit_ai.update@ (decisions) — the two scripts the shipped
--   @init_loader.lua@ schedules every 0.1 s, which is 'stepDt'. Nothing
--   in the fixture writes a stat or stubs an action; elapsed time per
--   occupant is the sum of the steps since the unit tick first reported
--   it alive.
--
--   After the bound the roster is killed, and the encounter must then
--   clear: the production clearance evaluator (the world thread's
--   @tickLocationDiscovery@) was live throughout, so "never cleared"
--   was an observation rather than an evaluator that never ran.
--
--   The world calendar is advanced by the world thread's own clock, not
--   by these steps, so "world age" in the late case means elapsed
--   engine seconds ('engine.gameTime'), the clock the issue measures.
--
--   __Local opt-in only (#2809).__ The two scenarios are actual game
--   simulations (10,800 engine seconds per occupant on a generated
--   world), and owner decision z3hd4feg (2026-10-08) makes those
--   optional, local only and never CI. They register no examples unless
--   @SYNARCHY_RUIN_SURVIVAL=1@ is set; any other value, or none,
--   registers nothing, and @SYNARCHY_FULL_TESTS@ does not enable them.
--   Neither CI nor @tools/ci-local.sh@ sets the variable. The nested
--   "survival exemption" group is finite and stays unconditional, so it
--   runs wherever this parent group runs. Run the two scenarios locally:
--
--   > SYNARCHY_RUIN_SURVIVAL=1 cabal-3.16.1.0 test synarchy-test-headless \
--   >   --test-options='--match "ruin occupant survival (#2754)"'
module Test.Headless.Unit.RuinOccupantSurvival (spec) where

import UPrelude
import Test.Hspec
import qualified Data.Text as T
import Control.Concurrent (threadDelay)
import Data.IORef (IORef, newIORef, readIORef, writeIORef, modifyIORef')
import Data.List (sort)
import System.Directory (listDirectory)
import System.Environment (lookupEnv)
import System.FilePath ((</>), takeExtension)
import Engine.Core.State (EngineEnv(..))
import Engine.PlayerEvent (PlayerEvent(..), StoredEvent(..))
import Engine.PlayerEvent.Emit (readEventLog)
import Engine.Scripting.Lua.Types (LuaBackendState)
import Test.Headless.Harness
    (moveCamera, waitForChunksAt, waitForWorldInit, withHeadlessEngine)
import Test.Headless.Unit.TransferApi (evalDebug, newBareLuaBackend)
import qualified Test.Headless.Unit.SurvivalExemption as SurvivalExemption
import Unit.Thread (UnitTickSeams(..), productionUnitTickSeams, unitTickWith)
import World.Chunk.Types (ChunkCoord(..))
import World.Page.Types (WorldPageId(..))

-- * The reported world (#2640's gate, seed 14)

pageName ∷ Text
pageName = "expedition"

worldSeed, worldSize, worldPlates ∷ Int
worldSeed   = 14
worldSize   = 64
worldPlates = 3

-- | The occupied ruin the issue reports.
ruinInstance ∷ Int
ruinInstance = 4

-- | The survival bound: elapsed engine seconds from each occupant's
--   own creation.
boundSec ∷ Double
boundSec = 10800

-- | The reported death arrived about 1,177 engine seconds into the
--   session; the late case spawns after at least that much world age.
lateSpawnAgeSec ∷ Double
lateSpawnAgeSec = 1200

-- | The shipped cadence of both Lua updates this drives
--   (@scripts\/init_loader.lua@), and below the unit tick's 0.25 s cap.
stepDt ∷ Double
stepDt = 0.1

-- * Content

-- | The shipped registries, in the order the #2640 gate loads them. The
--   unit registry is loaded whole so faction tags and equipment classes
--   resolve exactly as they do in a session; locations load last.
contentDirs ∷ [(FilePath, Text)]
contentDirs =
    [ ("data/substances",  "engine.loadSubstanceYaml")
    , ("data/items",       "engine.loadItemYaml")
    , ("data/equipment",   "engine.loadEquipmentYaml")
    , ("data/materials",   "engine.loadMaterialYaml")
    , ("data/factions",    "engine.loadFactionYaml")
    , ("data/units",       "engine.loadUnitYaml")
    , ("data/loot_tables", "engine.loadLootTableYaml") ]

loadContent ∷ LuaBackendState → IO ()
loadContent ls = do
    forM_ contentDirs $ \(dir, fn) → do
        files ← sort ∘ filter ((≡ ".yaml") ∘ takeExtension)
                    <$> listDirectory dir
        forM_ files $ \f →
            evalDebug ls (fn <> "('" <> T.pack (dir </> f) <> "')")
    _ ← evalDebug ls "engine.loadLocationYaml('data/locations/ruin_small.yaml')"
    pure ()

-- * The Lua half: the production modules, and read-only observation

-- | Requires the production modules (unit_ai FIRST — its satellites
--   extend the singleton), initializes the two scheduled scripts the way
--   @engine.loadScript@ does, and installs the observer. The observer
--   only READS: positions, poses, stats, inventories and the placed
--   instance. Its step function runs the two real updates and then
--   checks every assigned occupant against requirement 3.
observerLua ∷ Text
observerLua = T.unlines
    [ "local ai = require('scripts.unit_ai')"
    , "local resources = require('scripts.unit_resources')"
    , "local brain = require('scripts.brain')"
    , "resources.init(0); ai.init(0)"
    , "local M = { created = {}, ev = {} }"
    , "_G.__rs = M"
    , "M.page = '" <> pageName <> "'"
    , "M.instance = " <> tshow ruinInstance
    , "M.bound = " <> tshow boundSec
    , "local function lower(t, k, v) if v and (t[k] == nil or v < t[k]) then t[k] = v end end"
    , "local function higher(t, k, v) if v and (t[k] == nil or v > t[k]) then t[k] = v end end"
    , "function M.instanceRow()"
    , "  return world.getLocationInstance(M.instance, M.page)"
    , "end"
    -- Every nomad the unit tick has made live gets its creation time the
    -- first time it is observed, before the roster is known, so none of
    -- an occupant's interval can go unmeasured.
    , "function M.noteCreations()"
    , "  local now = engine.gameTime()"
    , "  for _, uid in ipairs(unit.getAllIds() or {}) do"
    , "    if M.created[uid] == nil then"
    , "      local info = unit.getInfo(uid)"
    , "      if info and info.defName == 'nomad_primitive' then"
    , "        M.created[uid] = now"
    , "        M.ev[uid] = {}"
    , "      end"
    , "    end"
    , "  end"
    , "end"
    , "function M.captureRoster()"
    , "  local row = M.instanceRow()"
    , "  local enc = row and row.encounter"
    , "  if not (enc and enc.roster_complete) then return false end"
    , "  M.rolled = enc.rolled_count"
    , "  M.roster = {}"
    , "  M.inRoster = {}"
    , "  for i, o in ipairs(enc.occupants or {}) do"
    , "    M.roster[i] = { uid = o.uid, home_x = o.home_x, home_y = o.home_y }"
    , "    M.inRoster[o.uid] = true"
    , "  end"
    , "  return true"
    , "end"
    , "local function fail(msg) M.failure = M.failure or string.format('t=%.1f %s', engine.gameTime(), msg); return M.failure end"
    , "local STEP = 0"
    -- The placed instance must keep its original roster and stay uncleared.
    , "function M.checkRoster()"
    , "  local row = M.instanceRow()"
    , "  local enc = row and row.encounter"
    , "  if not enc then return fail('placed instance lost its encounter') end"
    , "  if enc.cleared then return fail('encounter.cleared became true') end"
    , "  if #(enc.occupants or {}) ~= #M.roster then return fail('roster size changed') end"
    , "  for i, o in ipairs(enc.occupants) do"
    , "    local r = M.roster[i]"
    , "    if o.uid ~= r.uid or o.home_x ~= r.home_x or o.home_y ~= r.home_y then"
    , "      return fail('roster entry ' .. i .. ' changed identity or home')"
    , "    end"
    , "  end"
    , "  return nil"
    , "end"
    -- Unfought means unfought: nobody else on the page, no wound anywhere.
    , "function M.checkUnfought()"
    , "  for _, uid in ipairs(unit.getAllIds() or {}) do"
    , "    if not M.inRoster[uid] then return fail('a non-occupant unit ' .. uid .. ' is on the page') end"
    , "  end"
    , "  for _, r in ipairs(M.roster) do"
    , "    if #(unit.getWounds(r.uid) or {}) > 0 then return fail('occupant ' .. r.uid .. ' was injured') end"
    , "  end"
    , "  return nil"
    , "end"
    , "function M.checkOccupant(uid, home)"
    , "  if not unit.exists(uid) then return fail('occupant ' .. uid .. ' is missing') end"
    , "  local pose = unit.getPose(uid)"
    , "  if pose == 'dead' then return fail('occupant ' .. uid .. ' died') end"
    , "  local state = brain.state(uid)"
    , "  if state == 'delirious' or state == 'unconscious' then"
    , "    return fail('occupant ' .. uid .. ' is ' .. state)"
    , "  end"
    , "  local info = unit.getInfo(uid)"
    , "  local d = math.max(math.abs(info.gridX - home.home_x), math.abs(info.gridY - home.home_y))"
    , "  if d > 0.5 then"
    , "    return fail(string.format('occupant %d left its post (Chebyshev %.2f)', uid, d))"
    , "  end"
    , "  return nil"
    , "end"
    -- The physiology record: what the survival systems read over the run.
    , "function M.sample(uid)"
    , "  local e = M.ev[uid]"
    , "  lower(e, 'minSalt', unit.getStat(uid, 'salt_conc'))"
    , "  lower(e, 'minConsciousness', brain.consciousness(uid))"
    , "  higher(e, 'maxCore', unit.getStat(uid, 'core_temp'))"
    , "  higher(e, 'maxSaltMeter', unit.getStat(uid, 'salt_imbalance'))"
    , "  higher(e, 'maxHeatMeter', unit.getStat(uid, 'hyperthermia'))"
    , "end"
    -- One step AFTER the unit tick: both scheduled updates, then the
    -- requirement checks. Returns '' while running, 'DONE' once every
    -- occupant has been exercised for the whole bound, or the failure.
    , "function M.step(dt)"
    , "  resources.update(dt)"
    , "  ai.update(dt)"
    , "  M.noteCreations()"
    , "  if M.failure then return M.failure end"
    , "  if not M.roster then return '' end"
    , "  STEP = STEP + 1"
    , "  if STEP % 10 == 0 then"
    , "    local bad = M.checkRoster() or M.checkUnfought()"
    , "    if bad then return bad end"
    , "  end"
    , "  local now, done = engine.gameTime(), true"
    , "  for _, r in ipairs(M.roster) do"
    , "    local bad = M.checkOccupant(r.uid, r)"
    , "    if bad then return bad end"
    , "    if STEP % 10 == 0 then M.sample(r.uid) end"
    , "    if now - M.created[r.uid] < M.bound then done = false end"
    , "  end"
    , "  return done and 'DONE' or ''"
    , "end"
    , "function M.rosterUids()"
    , "  local t = {}"
    , "  for i, r in ipairs(M.roster or {}) do t[i] = tostring(r.uid) end"
    , "  return table.concat(t, ',')"
    , "end"
    -- The acceptance verdict over the whole run: '' when it holds.
    , "function M.verdict()"
    , "  if not M.roster then return 'roster never completed' end"
    , "  if not (M.rolled and M.rolled > 0) then return 'encounter rolled no occupants' end"
    , "  if #M.roster ~= M.rolled then return 'roster size does not match rolled_count' end"
    , "  local bad = M.checkRoster() or M.checkUnfought(); if bad then return bad end"
    , "  local now = engine.gameTime()"
    , "  for _, r in ipairs(M.roster) do"
    , "    if not M.created[r.uid] then return 'occupant ' .. r.uid .. ' was never observed alive' end"
    , "    if now - M.created[r.uid] < M.bound then return 'occupant ' .. r.uid .. ' ran short of the bound' end"
    , "  end"
    , "  return ''"
    , "end"
    , "function M.killRoster()"
    , "  for _, r in ipairs(M.roster) do unit.kill(r.uid) end"
    , "  return true"
    , "end"
    , "function M.cleared()"
    , "  local row = M.instanceRow()"
    , "  return row and row.encounter and row.encounter.cleared == true"
    , "end"
    , "function M.summary()"
    , "  local out = { string.format('seed=14 size=64 plates=3 page=%s ruin=%d rolled=%s spawn_age=%.1f now=%.1f',"
    , "    M.page, M.instance, tostring(M.rolled), M.spawnAge or -1, engine.gameTime()) }"
    , "  for _, r in ipairs(M.roster or {}) do"
    , "    local uid = r.uid"
    , "    local e = M.ev[uid] or {}"
    , "    local clim = world.getClimateAt(math.floor(r.home_x), math.floor(r.home_y)) or {}"
    , "    local amb = world.getAmbientAt(math.floor(r.home_x), math.floor(r.home_y))"
    , "    out[#out + 1] = string.format("
    , "      'uid=%d home=(%.1f,%.1f) created=%.1f elapsed=%.1f ambient=%.1fC humidity=%.2f min_salt_conc=%.3f min_consciousness=%.3f max_core=%.2f max_salt_meter=%.3f max_heat_meter=%.3f',"
    , "      uid, r.home_x, r.home_y, M.created[uid] or -1, engine.gameTime() - (M.created[uid] or 0),"
    , "      amb or -99, clim.humidity or -1, e.minSalt or -1, e.minConsciousness or -1,"
    , "      e.maxCore or -1, e.maxSaltMeter or -1, e.maxHeatMeter or -1)"
    , "  end"
    , "  return table.concat(out, ' || ')"
    , "end"
    , "return true"
    ]

-- | A debug-console result with its JSON string quoting removed.
luaText ∷ LuaBackendState → Text → IO Text
luaText ls src = T.strip ∘ T.dropAround (≡ '"') <$> evalDebug ls src

-- * The stepped simulation

data Clock = Clock
    { clkNow   ∷ IORef Double
    , clkLast  ∷ IORef Double
    , clkSeams ∷ UnitTickSeams }

newClock ∷ IO Clock
newClock = do
    now  ← newIORef 0
    lastT ← newIORef 0
    pure Clock
        { clkNow = now, clkLast = lastT
        , clkSeams = productionUnitTickSeams
            { tickClock = readIORef now
            , tickSleep = \_ → pure () } }

-- | One real unit tick after advancing the scripted clock by @dt@.
unitTick ∷ EngineEnv → Clock → Double → IO ()
unitTick env clk dt = do
    modifyIORef' (clkNow clk) (+ dt)
    void (unitTickWith (clkSeams clk) env (clkLast clk) (utsRef env))

-- | Step until the observer reports DONE or a failure, bounded well past
--   the bound so a stalled clock cannot loop forever.
runBound ∷ EngineEnv → Clock → LuaBackendState → IO Text
runBound env clk ls = go (0 ∷ Int)
  where
    cap = ceiling ((boundSec + 600) / stepDt)
    go n
      | n ≥ cap = pure "step cap reached before every occupant finished the bound"
      | otherwise = do
          unitTick env clk stepDt
          r ← luaText ls "return __rs.step(0.1)"
          if T.null r then go (n + 1) else pure r

-- | World age before the stamp: the same steps with no occupant yet.
preRoll ∷ EngineEnv → Clock → LuaBackendState → Double → IO ()
preRoll env clk ls age = go
  where
    go = do
        t ← readIORef (gameTimeRef env)
        when (t < age) $ do
            unitTick env clk stepDt
            _ ← luaText ls "return __rs.step(0.1)"
            go

-- | Boot the reported world, optionally age it, stamp ruin 4 through the
--   production hook, then run every occupant through the bound.
scenario ∷ Double → EngineEnv → IO ()
scenario spawnAge env = do
    ls ← newBareLuaBackend env
    loadContent ls
    installed ← luaText ls observerLua
    installed `shouldBe` "true"
    writeIORef (gameTimeRef env) 0

    _ ← evalDebug ls $ "world.init('" <> pageName <> "', " <> tshow worldSeed
        <> ", " <> tshow worldSize <> ", " <> tshow worldPlates
        <> ", 'First Expedition')"
    ws ← waitForWorldInit env (WorldPageId pageName) 300
    _ ← evalDebug ls $ "world.show('" <> pageName <> "')"

    ruin ← luaText ls $ T.concat
        [ "local r = __rs.instanceRow(); if not r then return 'none' end; "
        , "return table.concat({ r.id, r.gx, r.gy, r.cx, r.cy, "
        , "  r.encounter and r.encounter.rolled_count or 0 }, ',')" ]
    (gx, gy, cx, cy, rolled) ← case T.splitOn "," ruin of
        ["ruin_small", a, b, c, d, e] →
            pure (readT a, readT b, readT c, readT d, readT e ∷ Int)
        _ → error ("ruin instance 4 is not an occupied ruin_small: " <> T.unpack ruin)
    rolled `shouldSatisfy` (> 0)

    clk ← newClock
    preRoll env clk ls spawnAge

    moveCamera env (fromIntegral gx) (fromIntegral gy)
    _ ← evalDebug ls $ "return world.loadChunksInRegion(" <> tshow (cx - 2) <> ","
        <> tshow (cy - 2) <> "," <> tshow (cx + 2) <> "," <> tshow (cy + 2) <> ")"
    loaded ← waitForChunksAt ws (ChunkCoord cx cy) 120
    loaded `shouldBe` True
    _ ← evalDebug ls "__rs.spawnAge = engine.gameTime()"
    _ ← evalDebug ls $ "require('scripts.location_stamper').onStampLocation('"
        <> pageName <> "', 'ruin_small', " <> tshow gx <> ", " <> tshow gy <> ")"
    -- A zero-length tick runs the queued spawns without moving the clock,
    -- and the world thread registers the roster on its own; wait (in real
    -- time) for that, so the checks start at every occupant's creation.
    unitTick env clk 0
    _ ← luaText ls "__rs.noteCreations(); return true"
    let awaitRoster n
          | n ≥ (600 ∷ Int) = expectationFailure "the encounter roster never completed"
          | otherwise = do
              ok ← luaText ls "return __rs.captureRoster()"
              unless (ok ≡ "true") $ threadDelay 50000 >> awaitRoster (n + 1)
    awaitRoster 0

    result ← runBound env clk ls
    summary ← luaText ls "return __rs.summary()"
    putStrLn ("  [#2754] " <> T.unpack summary)
    unless (result ≡ "DONE") $ expectationFailure $
        T.unpack result <> "\n  " <> T.unpack summary
    verdict ← luaText ls "return __rs.verdict()"
    unless (T.null verdict) $ expectationFailure $
        T.unpack verdict <> "\n  " <> T.unpack summary

    uids ← map readT ∘ T.splitOn "," <$> luaText ls "return __rs.rosterUids()"
    rows ← readEventLog env
    let deaths = [ peText e | StoredEvent _ e ← rows
                 , peCategory e ≡ "survival_critical"
                 , maybe False ((`elem` uids) ∘ fromIntegral) (peUid e) ]
    deaths `shouldBe` []

    -- Non-vacuity: the production clearance evaluator (the world thread's
    -- tickLocationDiscovery) was live the whole time. Killing the roster
    -- now must clear the encounter, so "stayed uncleared" above was a
    -- real observation rather than an evaluator that never ran.
    _ ← luaText ls "return __rs.killRoster()"
    unitTick env clk stepDt
    let awaitCleared n
          | n ≥ (600 ∷ Int) = expectationFailure
              "killing the whole roster never cleared the encounter"
          | otherwise = do
              c ← luaText ls "return __rs.cleared()"
              unless (c ≡ "true") $ threadDelay 50000 >> awaitCleared (n + 1)
    awaitCleared 0
  where
    readT ∷ Read a ⇒ Text → a
    readT = read ∘ T.unpack

spec ∷ Spec
spec = describe "ruin occupant survival (#2754)" $ do
    -- The two long simulations need the exact local opt-in (#2809); the
    -- finite nested group below is unconditional.
    optIn ← runIO (lookupEnv "SYNARCHY_RUIN_SURVIVAL")
    when (optIn ≡ Just "1") $ do
        it "keeps an early-spawned ruin roster alive, lucid and on post for \
           \10,800 engine seconds each" $
            withHeadlessEngine (scenario 0)
        it "keeps a roster spawned into a 1,200-second-old world alive, lucid \
           \and on post for 10,800 engine seconds each" $
            withHeadlessEngine (scenario lateSpawnAgeSec)
    SurvivalExemption.spec
