#!/usr/bin/env python3
"""The manual-only probe census PAGE: generate it, and audit it (#1431).

`docs/probe_census.json` stays the authoritative global manifest —
every registered probe exactly once, CI-eligible and manual-only alike,
with its retained history. This renders the READABLE half of it,
`docs/probe_census.md`: one row per MANUAL-ONLY probe, in stable key
order. Nothing here writes, migrates or repairs the manifest.

THE PAGE HAS TWO SOURCES AND NEEDS BOTH. The manifest holds each
probe's classification, protocol status, acceptable-failure policy,
duration estimate and measurements; it does NOT hold #1440's reason
records, which live in `tools/ci_probes.py`'s `MANUAL_ONLY_REASONS`.
Joining them is what lets one row answer both "why is this probe not in
the blocking gate?" and "how flaky is it, on which commit, how long
ago?".

WHICH PROBES APPEAR IS DERIVED, NEVER LISTED. The row set is exactly
`ALL_KEYS - CI_ELIGIBLE`, computed from the live registries, so a newly
registered probe appears the day it registers and a promoted one leaves
the page the day it is promoted — while keeping its manifest row, its
policy and its whole archived history. Promotion is also a STORAGE
invariant, not just a display one: `probe_flake.resolve_probe` refuses
to MEASURE a CI-eligible probe and `probe_census.record_result` refuses
to RECORD one, so "receives no further census samples" holds even for a
result document produced before the promotion.

THE SOURCE MANIFEST IS VALIDATED BEFORE EITHER OPERATION. A missing,
duplicate, extra, stale-classification or stale-protocol row in the
manifest would otherwise yield a subset page that looks perfectly
consistent with itself; `--generate` and `--audit` both refuse on the
manifest first, with `probe_census`'s own shape check and inventory
comparison, and only then touch the page.

THE THREE MEASUREMENT STATES ARE EXPLICIT, and the ladder is
cohort-first. A row with a current cohort reports it (`measured`). A
row with none is `not yet measurable` when its protocol status is
`legacy` — `probe_flake` refuses to run a legacy probe at all, so there
is nothing to measure yet — and `not yet measured` when it has been
migrated to the protocol and simply has no sample on any commit. A
legacy row that nonetheless carries a cohort reports the cohort:
`probe_flake` cannot produce one, but hiding a stored measurement
behind "not yet measurable" would be a lie rather than a safeguard.
`unset` (no acceptable-failure policy) and `unknown` (no duration
estimate) are their own explicit cells for the same reason: an absent
value never renders as a zero.

RATE IS POOLED, NEVER AVERAGED. A row's rate is the current cohort's
total `failure_count` over its total `requested_runs`, which is
`probe_census.cohort_statistic`'s own arithmetic — averaging the stored
per-sample rates would weight a three-run measurement like a ten-run
one. Age runs from that cohort's freshness anchor (its latest
contributing measurement) to the as-of time the page DECLARES, so the
audit recomputes exactly the number the generator rendered.

The page lives beside the manifest, in the worktree whose branch is
`docs-wip`, and is neither published nor landed by this tool. Nothing
here enters `make ci` or GitHub CI: both commands, and
`tools/test_probe_census_page.py`, are manual-only.

Usage:
  python3 tools/probe_census_page.py --generate
  python3 tools/probe_census_page.py --generate --as-of 2026-08-21T05:00:00Z
  python3 tools/probe_census_page.py --audit
  python3 tools/test_probe_census_page.py        # the self-test

Exit codes: 0 success; 2 a missing or unusable docs worktree; 1 every
controlled refusal and every audit finding.
"""
from __future__ import annotations

import argparse
import datetime
import json
import math
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ci_probes  # noqa: E402
import probe_census  # noqa: E402
import probe_protocol  # noqa: E402
import probe_runner_registry  # noqa: E402

PAGE_RELPATH = "docs/probe_census.md"
# Deliberately NOT a `probe_census.STAGING_PREFIX` extension: the census
# writer sweeps every sibling carrying that prefix under its own lock,
# which would let it unlink this generator's live staging file.
PAGE_STAGING_PREFIX = ".probe_page."

TITLE = "# Manual-only probe census"
GENERATED_NOTE = ("<!-- Generated by `python3 tools/probe_census_page.py "
                  "--generate`. Do not hand-edit. -->")
PROSE = [
    "Generated from `docs/probe_census.json` — the authoritative global",
    "manifest, which holds every registered probe — joined with the",
    "manual-only reason records in `tools/ci_probes.py`. Only manual-only",
    "probes are listed. A probe promoted to CI eligibility keeps its manifest",
    "row, its acceptable-failure policy and its whole archived history; it",
    "leaves this page and receives no further census samples.",
    "",
    "Ages are measured against the as-of time below, which is why it is",
    "recorded here: `--audit` recomputes every age from it. Neither command",
    "runs in `make ci` or GitHub CI.",
]

# The table, column by column. The order is the rendered order, and
# every column except the key is independently audited.
COLUMNS = ("probe", "protocol", "reasons", "state", "rate", "X",
           "worst case", "commit", "age")

# Header fields, one per line, parsed back by `parse_page`.
FIELD_AS_OF = "as-of"
FIELD_REGISTERED = "registered"
FIELD_CI_ELIGIBLE = "ci-eligible"
FIELD_MANUAL_ONLY = "manual-only"
FIELD_RE = re.compile(r"^- \*\*([a-z0-9 -]+):\*\* (.*)$")

# An absent value is never a zero, an empty cell or a blank.
ABSENT = "-"
STATE_MEASURED = "measured"
STATE_NOT_MEASURABLE = "not yet measurable"
STATE_NOT_MEASURED = "not yet measured"
X_UNSET = "unset"
DURATION_UNKNOWN = "unknown"
# A cohort whose samples requested no runs at all has no denominator,
# which is a different observation from a failure rate of zero.
RATE_NO_DENOMINATOR = "n/a"


class PageError(probe_census.CensusError):
    """A controlled refusal: exit non-zero, write no page.

    A subclass of `CensusError` so one `except` in the CLI covers a
    refusal from either module, and so a caller embedding this tool
    never has to know which layer refused.
    """


# ==========================================================================
# The registries this page is derived from
# ==========================================================================
def registered_keys() -> set:
    """Every registered probe key, read from `probe_runner_registry.PROBES`.

    Read from the registry rather than `ci_probes.ALL_KEYS`, which is
    computed once at import: a test pointing the registry at a
    synthetic probe set must move this too, or it would audit a page
    against the shipped ninety.
    """
    return {key for key, _script, _purpose in probe_runner_registry.PROBES}


def manual_only_keys() -> list:
    """`ALL_KEYS - CI_ELIGIBLE`, in the page's stable key order."""
    return sorted(registered_keys() - set(ci_probes.CI_ELIGIBLE))


def source_problems(document) -> list[str]:
    """Every reason `document` cannot be a page's source manifest.

    Shape first, then inventory — the same ordering, and the same two
    checks, `probe_census --validate` applies: a document that is not a
    census at all should say so rather than be reported as ninety
    missing probes. Inventory drift matters here for a reason peculiar
    to a SUBSET page: a manifest missing a manual-only row, or carrying
    a stale classification, would produce a page that is internally
    consistent and quietly wrong about which probes exist.

    #1430's acceptable-failure policy is deliberately NOT applied here.
    A null X is state this page must be able to DISPLAY (`unset`), not
    a reason to refuse to render it, and a policy problem is
    `probe_census --validate`'s report either way.
    """
    try:
        probe_census.validate_census(document, "the source census")
    except probe_census.CensusError as error:
        problems = [str(error)]
    else:
        problems = probe_census.validate_manifest(document)
    # Tagged here rather than at each call site, so `--generate`,
    # `--audit` and a direct `audit_page` caller all say the same thing
    # about the same problem: this is the manifest, not the page.
    return [f"the source census {probe_census.MANIFEST_RELPATH} is not "
            f"usable: {problem}" for problem in problems]


# ==========================================================================
# Cells
# ==========================================================================
def _cell(value: str, where: str) -> str:
    """A rendered cell, refused if it would break out of the table."""
    if "|" in value or "\n" in value:
        raise PageError(
            f"{where} cannot be rendered in a table cell: {value!r}")
    return value


def _number(value, where: str) -> str:
    """A finite number in its shortest round-tripping spelling."""
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise PageError(
            f"{where} must be a number, got {type(value).__name__}")
    if not math.isfinite(value):
        raise PageError(f"{where} must be finite, got {value!r}")
    return json.dumps(value)


def _rate_cell(statistic: dict) -> str:
    """The pooled rate, with the counts it was pooled from."""
    requested = statistic["requested_runs"]
    failures = statistic["failure_count"]
    rate = statistic["failure_rate"]
    if rate is None:
        return f"{RATE_NO_DENOMINATOR} ({failures}/{requested})"
    return f"{rate * 100:.1f}% ({failures}/{requested})"


def _age_cell(as_of, anchor) -> str:
    """Age in days, clamped at zero.

    A cohort anchored after the as-of time — a skewed clock, or an
    as-of deliberately set in the past — is the freshest thing there
    is, never negatively old.
    """
    seconds = max(0.0, (as_of - anchor).total_seconds())
    return f"{seconds / probe_census.SECONDS_PER_DAY:.1f} d"


def _acceptable_failures_cell(census, key: str) -> str:
    value = census.get("acceptable_failures")
    if value is None:
        return X_UNSET
    if isinstance(value, bool) or not isinstance(value, int):
        raise PageError(
            f"probe {key!r} has an unusable acceptable-failure policy "
            f"({value!r}); `python3 tools/probe_census.py --validate` reports "
            f"it")
    return str(value)


def _duration_cell(census, key: str) -> str:
    value = census.get("estimated_worst_case_seconds")
    if value is None:
        return DURATION_UNKNOWN
    return f"{_number(value, f'probe {key!r} estimated worst case')} s"


def _measurement_state(entry: dict, key: str):
    """This row's state, and the cohort it reports (or None).

    Cohort-first: a stored current cohort is reported whatever the
    protocol status says, because it is evidence a measurement happened.
    Only a row with no cohort is classified by protocol.
    """
    census = entry.get("census")
    if not isinstance(census, dict):
        raise PageError(f"probe {key!r} has no census record")
    current = census.get("current")
    if isinstance(current, dict):
        return STATE_MEASURED, current
    if current is not None:
        raise PageError(
            f"probe {key!r} has a `current` cohort that is not an object "
            f"({type(current).__name__})")
    if entry.get("protocol") != probe_protocol.PROTOCOL_VERSION:
        return STATE_NOT_MEASURABLE, None
    return STATE_NOT_MEASURED, None


# ==========================================================================
# Rows
# ==========================================================================
def _entries(document) -> dict:
    """The manifest's rows by key, refusing a shape that has none."""
    if not isinstance(document, dict):
        raise PageError(
            f"the census must be a JSON object, got {type(document).__name__}")
    rows = document.get("probes")
    if not isinstance(rows, list):
        raise PageError("the census `probes` must be a list")
    found: dict = {}
    for position, entry in enumerate(rows):
        if not isinstance(entry, dict) or not isinstance(entry.get("key"), str):
            raise PageError(
                f"census entry {position} has no string `key`: {entry!r}")
        key = entry["key"]
        if key in found:
            raise PageError(f"the census holds duplicate rows for {key!r}")
        found[key] = entry
    return found


def build_rows(document, *, as_of, reasons=None) -> list[dict]:
    """One rendered row per manual-only probe, in stable key order.

    Every cell is produced here, so the generator and the audit derive
    the page from one implementation rather than two that can drift.
    """
    if not isinstance(as_of, datetime.datetime) or as_of.tzinfo is None:
        raise PageError("the as-of time must be a timezone-aware datetime")
    records = (ci_probes.MANUAL_ONLY_REASONS if reasons is None else reasons)
    shape = ci_probes.validate_manual_only_reasons(records)
    if shape:
        raise PageError(
            f"the manual-only reason registry is unusable: {shape[0]}"
            + (f" (and {len(shape) - 1} more)" if len(shape) > 1 else ""))
    entries = _entries(document)
    rows = []
    for key in manual_only_keys():
        entry = entries.get(key)
        if entry is None:
            raise PageError(
                f"the census has no row for manual-only probe {key!r}")
        declared = records.get(key)
        if not declared:
            raise PageError(
                f"tools/ci_probes.py records no manual-only reason for "
                f"{key!r}, so the page cannot say why it is out of CI")
        state, cohort = _measurement_state(entry, key)
        if cohort is None:
            rate = commit = age = ABSENT
        else:
            statistic, anchor = probe_census.cohort_statistic(
                cohort, f"probe {key!r} current cohort")
            rate = _rate_cell(statistic)
            commit = statistic["commit_sha"]
            age = _age_cell(as_of, anchor)
        census = entry["census"]
        row = {
            "probe": key,
            "protocol": str(entry.get("protocol")),
            # Declared order (#1440), never sorted: it is the order the
            # registry states the grounds in.
            "reasons": ", ".join(record.category for record in declared),
            "state": state,
            "rate": rate,
            "X": _acceptable_failures_cell(census, key),
            "worst case": _duration_cell(census, key),
            "commit": commit,
            "age": age,
        }
        rows.append({column: _cell(row[column], f"probe {key!r} {column}")
                     for column in COLUMNS})
    return rows


# ==========================================================================
# Rendering
# ==========================================================================
def _table(rows: list[dict]) -> list[str]:
    """The markdown table, padded to fixed columns for readability."""
    # At least three, so every separator cell is a valid `---` even
    # when the widest value in a column is one character.
    widths = {column: max(3, len(column),
                          *(len(row[column]) for row in rows))
              for column in COLUMNS}
    def line(cells) -> str:
        return "| " + " | ".join(
            f"{cells[column]:<{widths[column]}}" for column in COLUMNS) + " |"
    lines = [line({column: column for column in COLUMNS}),
             line({column: "-" * widths[column] for column in COLUMNS})]
    lines.extend(line(row) for row in rows)
    return lines


def render_page(document, *, as_of, reasons=None) -> str:
    """The whole page: a pure function of the census, the as-of and the
    live registries, so two runs on unchanged inputs are byte-identical.
    """
    rows = build_rows(document, as_of=as_of, reasons=reasons)
    registered = len(registered_keys())
    lines = [TITLE, "", GENERATED_NOTE, ""]
    lines.extend(PROSE)
    lines.extend([
        "",
        f"- **{FIELD_AS_OF}:** {as_of.strftime(probe_census.TIMESTAMP_FORMAT)}",
        f"- **{FIELD_REGISTERED}:** {registered}",
        f"- **{FIELD_CI_ELIGIBLE}:** {registered - len(rows)}",
        f"- **{FIELD_MANUAL_ONLY}:** {len(rows)}",
        "",
    ])
    lines.extend(_table(rows))
    return "\n".join(lines) + "\n"


# ==========================================================================
# Parsing a rendered page back
# ==========================================================================
def _cells(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def parse_page(text) -> tuple[dict, list[dict]]:
    """A rendered page as its header fields and its data rows.

    Structural refusals raise: a page whose table is not the generated
    one cannot have its rows compared field by field, and reporting one
    structural cause beats reporting ninety derived ones.
    """
    if not isinstance(text, str):
        raise PageError(f"the page must be text, got {type(text).__name__}")
    fields: dict = {}
    table: list[str] = []
    for line in text.splitlines():
        stripped = line.rstrip()
        match = FIELD_RE.match(stripped)
        if match:
            name = match.group(1)
            if name in fields:
                # First-wins would let a second, CONTRADICTING `as-of`
                # line sit under a page whose ages were computed from
                # the first one, and audit clean. The generator emits
                # each field exactly once, so a repeat is never a page
                # this tool wrote.
                raise PageError(
                    f"the page declares `{name}` more than once "
                    f"({fields[name]!r}, then {match.group(2).strip()!r}); "
                    f"a generated page declares each header field once")
            fields[name] = match.group(2).strip()
            continue
        if stripped.startswith("|"):
            table.append(stripped)
    if not table:
        raise PageError("the page holds no table at all")
    header = _cells(table[0])
    if header != list(COLUMNS):
        raise PageError(
            f"the page's table header is {header}, expected {list(COLUMNS)}")
    if len(table) < 2:
        raise PageError("the page's table has no separator row")
    separator = _cells(table[1])
    if len(separator) != len(COLUMNS) or not all(
            len(cell) >= 3 and set(cell) == {"-"} for cell in separator):
        raise PageError(
            f"the page's table separator row is {separator}, expected one "
            f"dashed cell per column")
    rows = []
    for offset, line in enumerate(table[2:], start=1):
        cells = _cells(line)
        if len(cells) != len(COLUMNS):
            raise PageError(
                f"table row {offset} has {len(cells)} cells, expected "
                f"{len(COLUMNS)}: {line!r}")
        rows.append(dict(zip(COLUMNS, cells)))
    return fields, rows


# ==========================================================================
# The audit
# ==========================================================================
def _why_not_listed(key: str) -> str:
    if key in set(ci_probes.CI_ELIGIBLE):
        return ("it is CI-eligible, so it keeps its manifest row and its "
                "history but takes no page row")
    if key not in registered_keys():
        return "it is not registered in probe_runner_registry.PROBES"
    return "it is not a manual-only probe"


def audit_page(text, document, *, reasons=None) -> list[str]:
    """Every disagreement between a rendered page and its two sources.

    Membership is the cheapest of the checks, not the whole of it: each
    surviving row is compared cell by cell against the row the same
    generator would render, so a hand-edited rate, protocol, reason
    set, state, X, duration, commit or age is a finding of its own.
    Missing, duplicate and extra rows are diagnosed independently, so
    one of them never masks another.
    """
    problems = source_problems(document)
    if problems:
        return problems
    try:
        fields, rows = parse_page(text)
    except probe_census.CensusError as error:
        return [str(error)]
    stamp = fields.get(FIELD_AS_OF)
    if stamp is None:
        return [f"the page declares no `{FIELD_AS_OF}` time, so no age in it "
                f"can be checked"]
    try:
        as_of = probe_census.parse_timestamp(
            stamp, f"the page's `{FIELD_AS_OF}` time")
        expected_rows = {row["probe"]: row for row in
                         build_rows(document, as_of=as_of, reasons=reasons)}
    except probe_census.CensusError as error:
        return [f"the page cannot be checked against the census: {error}"]

    findings: list[str] = []
    expected_keys = manual_only_keys()
    registered = len(registered_keys())
    for field, want in ((FIELD_REGISTERED, registered),
                        (FIELD_CI_ELIGIBLE, registered - len(expected_keys)),
                        (FIELD_MANUAL_ONLY, len(expected_keys))):
        got = fields.get(field)
        if got != str(want):
            findings.append(
                f"the page reports `{field}` as {got!r}, expected {want}")

    positions: dict = {}
    for index, row in enumerate(rows, start=1):
        positions.setdefault(row["probe"], []).append(index)
    for key, where in positions.items():
        if len(where) > 1:
            findings.append(
                f"duplicate rows for probe {key!r} (rows "
                f"{', '.join(str(index) for index in where)})")
    for key in positions:
        if key not in expected_rows:
            findings.append(
                f"extra row for probe {key!r}: {_why_not_listed(key)}")
    for key in expected_keys:
        if key not in positions:
            findings.append(f"missing row for probe {key!r}")
    order = [row["probe"] for row in rows]
    if sorted(order) == expected_keys and order != expected_keys:
        findings.append(
            "the page's rows are not in stable key order: "
            f"{order[:5]}{'...' if len(order) > 5 else ''}")

    for row in rows:
        expected = expected_rows.get(row["probe"])
        if expected is None:
            continue
        for column in COLUMNS[1:]:
            if row[column] != expected[column]:
                findings.append(
                    f"probe {row['probe']!r}: page {column} {row[column]!r} "
                    f"disagrees with its sources ({expected[column]!r})")
    return findings


# ==========================================================================
# The docs worktree
# ==========================================================================
def page_path(repo_root: str | None = None) -> Path:
    return probe_census.resolve_docs_worktree(repo_root) / PAGE_RELPATH


def write_page(path: Path, text: str) -> None:
    """Install `text` as the page, atomically, refusing a swapped path.

    The census writer's own substitution refusal and atomic replacement
    are reused deliberately rather than reimplemented: this writes into
    the same directory, with the same symlink and hard-link hazards,
    and a second fsync-then-rename dance would be a second thing to get
    wrong. No LOCK is taken, and none is needed — generating a page is
    a whole-file replacement rather than a read-modify-write, so two
    concurrent generators cannot interleave and every reader sees one
    complete page or the other.
    """
    target = Path(path)
    probe_census._refuse_substituted(target, "census page")
    probe_census._atomic_replace(target, text.encode("utf-8"),
                                 what="census page",
                                 prefix=PAGE_STAGING_PREFIX)


def read_page(path: Path) -> str:
    try:
        return Path(path).read_text(encoding="utf-8")
    except OSError as error:
        raise PageError(
            f"the census page {path} is unreadable ({error}). Generate it "
            f"with `python3 tools/probe_census_page.py --generate`.") from None


# ==========================================================================
# CLI
# ==========================================================================
def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--generate", action="store_true",
                       help=f"render {PAGE_RELPATH} into the "
                            f"{probe_census.DOCS_BRANCH} worktree")
    group.add_argument("--audit", action="store_true",
                       help="check the rendered page against the census and "
                            "the live registries")
    ap.add_argument("--as-of", metavar="TIMESTAMP",
                    help="the UTC evaluation time --generate records and "
                         "measures every age against, as "
                         "`YYYY-MM-DDTHH:MM:SSZ` (default: now)")
    args = ap.parse_args(argv)

    try:
        if args.as_of is not None and not args.generate:
            raise PageError(
                "--as-of belongs to --generate: --audit measures every age "
                "against the as-of time the page itself declares")
        as_of = (datetime.datetime.now(datetime.timezone.utc)
                 if args.as_of is None
                 else probe_census.parse_timestamp(args.as_of, "--as-of"))
        document = probe_census.load(probe_census.manifest_path())
        path = page_path()
        # The source manifest is validated FIRST, for both operations and
        # before the page is even read. `--audit` used to read the page
        # first, so a stale manifest beside a missing page reported the
        # missing page — the one diagnosis that does not name the thing
        # actually wrong. `audit_page` repeats the check for a caller
        # that reaches it directly; running it twice costs nothing and
        # keeps neither side dependent on the other's ordering.
        problems = source_problems(document)
        if not problems:
            if args.generate:
                write_page(path, render_page(document, as_of=as_of))
            else:
                problems = audit_page(read_page(path), document)
    except probe_census.DocsWorktreeMissing as error:
        print(f"probe_census_page: {error}", file=sys.stderr)
        return 2
    except probe_census.CensusError as error:
        print(f"probe_census_page: {error}", file=sys.stderr)
        return 1
    except ValueError as error:
        print(f"probe_census_page: {error}", file=sys.stderr)
        return 1
    if problems:
        for problem in problems:
            print(f"probe_census_page: {problem}", file=sys.stderr)
        return 1
    count = len(manual_only_keys())
    if args.generate:
        print(f"wrote {path}: {count} manual-only probes of "
              f"{len(registered_keys())} registered")
    else:
        print(f"{path}: {count} manual-only rows agree with "
              f"{probe_census.MANIFEST_RELPATH} and tools/ci_probes.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
