#!/usr/bin/env python3
"""world_audit.py's checks over synthetic grids and one real dump (#2070).

Constructs synthetic tile grids that exercise each check and verifies the
audit correctly identifies the issue it is meant to catch: the clean-grid
summary and canonical issue ordering; the dry/ocean/river/lake/fluid
checks; lava depth, rim containment and incomplete-window handling;
terrain spikes and pits; river gaps and mouth drops; islands, isolated
fluid, minimum-bound leaks and surface consistency; inland versus
ocean-connected below-sea terrain; and the wetland and desert slope checks.

One group reads no grid at all: `test_registry_composition_fails_closed`
drives `world_audit.compose_checks` over stand-in owners and pins the six
ways the #2224 split could silently shorten the audit, plus that
`audit_dump` runs every registered check exactly once.

The grid builders (`tile`, `flat_grid`, `make_tiles`, `count_category`,
`issue_coords`) live here because this is their only consumer.

One group reads real output rather than a hand-built grid:
`test_lava_rim_on_real_generated_output` drives the tracked
`tools/fixtures/dump_seed12321_lava_pool.json`, which is read-only
evidence and is never regenerated by this suite.

Not a gate of its own. Run through the aggregate:

  python3 tools/test_audit.py
"""
from __future__ import annotations

import json
import sys
import types
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import world_audit  # type: ignore  # noqa: E402
from world_audit import audit_dump, INT64_MIN, neighbors4  # type: ignore  # noqa: E402
from test_audit_support import expect  # noqa: E402


def tile(x: int, y: int, terrainZ: int = 1,
         fluidType: str | None = None, fluidSurf: int | None = None,
         matId: int = 56,  # loam — neutral; 62-64 trip WETLAND_ON_SLOPE
         glacierZone: bool = False, beyondGlacier: bool = False) -> dict[str, Any]:
    if fluidType is None:
        surfaceZ = terrainZ
    else:
        surfaceZ = max(terrainZ, fluidSurf if fluidSurf is not None else terrainZ)
    return {
        "x": x, "y": y, "v": x + y,
        "terrainZ": terrainZ,
        "surfaceZ": surfaceZ,
        "matId": matId,
        "fluidType": fluidType,
        "fluidSurf": fluidSurf,
        "iceSurf": None,
        "iceMode": None,
        "glacierZone": glacierZone,
        "beyondGlacier": beyondGlacier,
    }


def flat_grid(w: int, h: int, x0: int = 0, y0: int = 0,
              terrainZ: int = 1,
              fluidType: str | None = None,
              fluidSurf: int | None = None) -> list[dict[str, Any]]:
    return [
        tile(x0 + dx, y0 + dy, terrainZ=terrainZ,
             fluidType=fluidType, fluidSurf=fluidSurf)
        for dy in range(h) for dx in range(w)
    ]


def make_tiles(tiles: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Normalize: drop duplicates (later overrides earlier)."""
    seen = {}
    for t in tiles:
        seen[(t["x"], t["y"])] = t
    return list(seen.values())


def count_category(result_dict: dict[str, Any], cat: str) -> int:
    return result_dict["summary"].get(cat, 0)


def test_dry_below_sea() -> None:
    print("test_dry_below_sea")
    tiles = flat_grid(5, 5, -2, -2, terrainZ=-1, fluidType="ocean", fluidSurf=0)
    # Turn one tile into dry with terrainZ=-1
    tiles[12] = tile(0, 0, terrainZ=-1, fluidType=None)
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "DRY_BELOW_SEA") == 1,
           f"DRY_BELOW_SEA count: {count_category(result, 'DRY_BELOW_SEA')}, expected 1")


def test_ocean_on_land() -> None:
    print("test_ocean_on_land")
    # Cascade bug: ocean tile with terrainZ > 5
    tiles = flat_grid(3, 3, -1, -1, terrainZ=1, fluidType="ocean", fluidSurf=0)
    tiles[4] = tile(0, 0, terrainZ=100, fluidType="ocean", fluidSurf=0)
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "OCEAN_ON_LAND") == 1,
           f"OCEAN_ON_LAND count: {count_category(result, 'OCEAN_ON_LAND')}, expected 1")


def test_river_under_terrain() -> None:
    print("test_river_under_terrain")
    # River tile where fluidSurf < terrainZ
    tiles = flat_grid(3, 3, -1, -1, terrainZ=5, fluidType=None)
    tiles[4] = tile(0, 0, terrainZ=10, fluidType="river", fluidSurf=5)
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "RIVER_UNDER_TERRAIN") == 1,
           f"RIVER_UNDER_TERRAIN count: {count_category(result, 'RIVER_UNDER_TERRAIN')}, expected 1")


def test_lake_under_terrain() -> None:
    print("test_lake_under_terrain")
    tiles = flat_grid(3, 3, -1, -1, terrainZ=5, fluidType=None)
    tiles[4] = tile(0, 0, terrainZ=10, fluidType="lake", fluidSurf=5)
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "LAKE_UNDER_TERRAIN") == 1,
           f"LAKE_UNDER_TERRAIN count: {count_category(result, 'LAKE_UNDER_TERRAIN')}, expected 1")


def test_floating_fluid() -> None:
    print("test_floating_fluid")
    # Lava with fluidSurf - terrainZ > 15. The lava depth metric is named
    # DEEP_LAVA_COLUMN (#1876) because that is all it measures; rim
    # geometry is test_lava_rim_containment below.
    tiles = flat_grid(3, 3, -1, -1, terrainZ=-50, fluidType="lava", fluidSurf=5)
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "DEEP_LAVA_COLUMN") == 9,
           f"DEEP_LAVA_COLUMN count: "
           f"{count_category(result, 'DEEP_LAVA_COLUMN')}, expected 9")
    expect(count_category(result, "FLOATING_LAVA") == 0,
           "FLOATING_LAVA must no longer name a depth-only lava count")

    # River with high depth
    tiles = flat_grid(3, 3, -1, -1, terrainZ=-50, fluidType="river", fluidSurf=5)
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "FLOATING_RIVER") == 9,
           f"FLOATING_RIVER count: {count_category(result, 'FLOATING_RIVER')}, expected 9")

    # Ocean at any depth should NOT trigger floating
    tiles = flat_grid(3, 3, -1, -1, terrainZ=-100, fluidType="ocean", fluidSurf=0)
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "DEEP_LAVA_COLUMN") == 0
           and count_category(result, "FLOATING_RIVER") == 0
           and count_category(result, "FLOATING_LAKE") == 0,
           "deep ocean should not trigger the depth metrics")


def issue_coords(result_dict: dict[str, Any], cat: str) -> list[tuple[int, int]]:
    return sorted((i["x"], i["y"]) for i in result_dict["issues"].get(cat, []))


def test_lava_rim_containment() -> None:
    """Containment is rim geometry, not column depth (#1876).

    The old FLOATING_LAVA predicate was `fluidSurf - terrainZ > 15` and
    inspected no neighbour, so it counted every deep pool — including the
    fully contained ones `World.Magma.Pool` is supposed to produce. These
    cases drive the real audit and pin the contained-versus-breached
    distinction the threshold raise in PR #255 established by hand and
    never encoded.
    """
    print("test_lava_rim_containment")

    # (a) The five-cell fixture from the issue: a 20-deep pool whose whole
    #     dry rim sits AT the lava surface. Contained at any depth.
    contained = [
        tile(0, 0, terrainZ=-20, fluidType="lava", fluidSurf=0),
        tile(-1, 0, terrainZ=0), tile(1, 0, terrainZ=0),
        tile(0, -1, terrainZ=0), tile(0, 1, terrainZ=0),
    ]
    result = audit_dump(contained).to_dict()
    expect(count_category(result, "LAVA_RIM_BREACH") == 0,
           f"contained deep pool: LAVA_RIM_BREACH "
           f"{count_category(result, 'LAVA_RIM_BREACH')}, expected 0")
    expect(count_category(result, "LAVA_RIM_INCOMPLETE") == 0,
           f"contained deep pool has all four neighbours present: "
           f"LAVA_RIM_INCOMPLETE "
           f"{count_category(result, 'LAVA_RIM_INCOMPLETE')}, expected 0")
    # The depth metric survives the rename and still sees this column.
    expect(count_category(result, "DEEP_LAVA_COLUMN") == 1,
           f"contained deep pool is still a deep COLUMN: DEEP_LAVA_COLUMN "
           f"{count_category(result, 'DEEP_LAVA_COLUMN')}, expected 1")

    # (b) The same pool with ONE rim tile a single z lower is breached.
    breached = [
        tile(0, 0, terrainZ=-20, fluidType="lava", fluidSurf=0),
        tile(-1, 0, terrainZ=-1), tile(1, 0, terrainZ=0),
        tile(0, -1, terrainZ=0), tile(0, 1, terrainZ=0),
    ]
    result = audit_dump(breached).to_dict()
    expect(issue_coords(result, "LAVA_RIM_BREACH") == [(0, 0)],
           f"one dry rim tile below the surface breaches the pool: "
           f"{issue_coords(result, 'LAVA_RIM_BREACH')}, expected [(0, 0)]")

    # (c) Equal elevation is contained, strictly below is not — the exact
    #     boundary, checked from both sides on the same geometry.
    for rim_z, expected in ((0, 0), (-1, 1)):
        tiles = [
            tile(0, 0, terrainZ=-20, fluidType="lava", fluidSurf=0),
            tile(-1, 0, terrainZ=rim_z), tile(1, 0, terrainZ=rim_z),
            tile(0, -1, terrainZ=rim_z), tile(0, 1, terrainZ=rim_z),
        ]
        result = audit_dump(tiles).to_dict()
        expect(count_category(result, "LAVA_RIM_BREACH") == expected,
               f"rim at terrainZ={rim_z} vs fluidSurf=0: LAVA_RIM_BREACH "
               f"{count_category(result, 'LAVA_RIM_BREACH')}, "
               f"expected {expected}")

    # (d) One offending TILE, not one offending edge: all four rim tiles
    #     below the surface still emit a single occurrence.
    tiles = [
        tile(0, 0, terrainZ=-20, fluidType="lava", fluidSurf=0),
        tile(-1, 0, terrainZ=-5), tile(1, 0, terrainZ=-5),
        tile(0, -1, terrainZ=-5), tile(0, 1, terrainZ=-5),
    ]
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "LAVA_RIM_BREACH") == 1,
           f"four lower rim tiles are one offending lava tile: "
           f"LAVA_RIM_BREACH {count_category(result, 'LAVA_RIM_BREACH')}, "
           f"expected 1")

    # (e) Water is a barrier the pool stops against, not a rim breach —
    #     World.Magma.Pool.isWater treats ocean/lake/river the same way.
    tiles = [
        tile(0, 0, terrainZ=-20, fluidType="lava", fluidSurf=0),
        tile(-1, 0, terrainZ=-30, fluidType="ocean", fluidSurf=0),
        tile(1, 0, terrainZ=-10, fluidType="lake", fluidSurf=-5),
        tile(0, -1, terrainZ=-10, fluidType="river", fluidSurf=-5),
        tile(0, 1, terrainZ=0),
    ]
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "LAVA_RIM_BREACH") == 0,
           f"ocean/lake/river neighbours are barriers: LAVA_RIM_BREACH "
           f"{count_category(result, 'LAVA_RIM_BREACH')}, expected 0")

    # (f) The world-boundary sentinel is a barrier too, on both spellings.
    tiles = [
        tile(0, 0, terrainZ=-20, fluidType="lava", fluidSurf=0),
        tile(-1, 0, terrainZ=INT64_MIN, beyondGlacier=True),
        tile(1, 0, terrainZ=INT64_MIN),
        tile(0, -1, terrainZ=0), tile(0, 1, terrainZ=0),
    ]
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "LAVA_RIM_BREACH") == 0,
           f"sentinel neighbours are barriers: LAVA_RIM_BREACH "
           f"{count_category(result, 'LAVA_RIM_BREACH')}, expected 0")

    # (g) A neighbour outside the dumped region proves nothing either way:
    #     the tile records an incomplete judgement and no breach.
    edge = [tile(0, 0, terrainZ=-20, fluidType="lava", fluidSurf=0)]
    result = audit_dump(edge).to_dict()
    expect(count_category(result, "LAVA_RIM_BREACH") == 0,
           f"absent neighbours never emit a breach: LAVA_RIM_BREACH "
           f"{count_category(result, 'LAVA_RIM_BREACH')}, expected 0")
    expect(issue_coords(result, "LAVA_RIM_INCOMPLETE") == [(0, 0)],
           f"a region-edge lava tile records one incomplete judgement: "
           f"{issue_coords(result, 'LAVA_RIM_INCOMPLETE')}, "
           f"expected [(0, 0)]")

    # (h) The two records are independent: a tile can be provably breached
    #     on a present neighbour while another is off-window.
    tiles = [
        tile(0, 0, terrainZ=-20, fluidType="lava", fluidSurf=0),
        tile(1, 0, terrainZ=-5),
    ]
    result = audit_dump(tiles).to_dict()
    expect(issue_coords(result, "LAVA_RIM_BREACH") == [(0, 0)]
           and issue_coords(result, "LAVA_RIM_INCOMPLETE") == [(0, 0)],
           f"breach and incomplete coexist: breach "
           f"{issue_coords(result, 'LAVA_RIM_BREACH')}, incomplete "
           f"{issue_coords(result, 'LAVA_RIM_INCOMPLETE')}, "
           f"expected both [(0, 0)]")

    # (i) A higher pool draining into a lower one is perched. The
    #     occurrence is filed against the HIGHER tile, and the lower tile
    #     — which is supported everywhere — reports nothing.
    perched = flat_grid(4, 3, -1, -1, terrainZ=10, fluidType=None)
    perched = make_tiles(perched)
    for i, cell in enumerate(perched):
        if (cell["x"], cell["y"]) == (0, 0):
            perched[i] = tile(0, 0, terrainZ=0, fluidType="lava", fluidSurf=10)
        elif (cell["x"], cell["y"]) == (1, 0):
            perched[i] = tile(1, 0, terrainZ=0, fluidType="lava", fluidSurf=2)
    result = audit_dump(perched).to_dict()
    expect(issue_coords(result, "LAVA_RIM_BREACH") == [(0, 0)],
           f"a lava neighbour with a strictly lower surface breaches the "
           f"HIGHER tile: {issue_coords(result, 'LAVA_RIM_BREACH')}, "
           f"expected [(0, 0)]")
    expect(count_category(result, "LAVA_RIM_INCOMPLETE") == 0,
           f"both perched-pair tiles have four present neighbours: "
           f"LAVA_RIM_INCOMPLETE "
           f"{count_category(result, 'LAVA_RIM_INCOMPLETE')}, expected 0")


FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures"


# A real `--dump` window, not a hand-built grid: seed 12321, worldSize 32,
# region -4,-4,4,4 (a tracked baseline seed), trimmed to the tiles within 3
# of its lava pool so every lava tile keeps all four real cardinal
# neighbours. Regenerate with:
#   cabal run -v0 exe:synarchy -- --dump --seed 12321 --worldSize 32 \
#       --region -4,-4,4,4
# then keep -12 <= x <= 4, 65 <= y <= 77.
REAL_LAVA_DUMP = FIXTURE_DIR / "dump_seed12321_lava_pool.json"


def real_lava_dump() -> list[dict[str, Any]]:
    return world_audit.load_dump_file(REAL_LAVA_DUMP)


def test_lava_rim_on_real_generated_output() -> None:
    """The containment check against REAL generator output, not a fixture.

    This is the case that keeps the predicate honest. On the shipped
    pipeline a pool's raw rim never reaches `--dump`: `poolRimCaps` raises
    every OUTERMOST pool tile to the pool surface as a basalt cap,
    `applyBasaltCaps` writes that terrain, and `applyLavaShell` then strips
    the zero-depth lava film off it (`src/World/Generate/Chunk.hs`). What
    the audit sees is the SEALED rim — a basalt wall flush with the lava —
    so a pool that `World.Magma.Pool.grow` truncated at its area or radius
    bound has already been repaired by the time the dump exists.

    So LAVA_RIM_BREACH is a live guard on that SEALING pipeline, and the
    zero it measures across the baselines is evidence the seal holds — not
    evidence that `grow` never truncates, which post-cap data cannot show
    either way. The mutation below is what proves the check is a guard
    rather than dead code: undo one real tile's cap and the breach appears.
    """
    print("test_lava_rim_on_real_generated_output")
    data = real_lava_dump()
    grid = {(t["x"], t["y"]): t for t in data}
    lava = [t for t in data if t["fluidType"] == "lava"]
    expect(len(lava) == 23,
           f"fixture holds the seed-12321 pool: {len(lava)} lava tiles, "
           f"expected 23")

    result = audit_dump(data).to_dict()
    # The same count seed 12321's tracked baseline records, so the fixture
    # is demonstrably that seed's real output and not a reduction of it.
    expect(count_category(result, "DEEP_LAVA_COLUMN") == 11,
           f"real dump reproduces the baseline's deep-column count: "
           f"{count_category(result, 'DEEP_LAVA_COLUMN')}, expected 11")
    expect(count_category(result, "LAVA_RIM_BREACH") == 0,
           f"the sealed rim is contained: LAVA_RIM_BREACH "
           f"{count_category(result, 'LAVA_RIM_BREACH')}, expected 0")
    expect(count_category(result, "LAVA_RIM_INCOMPLETE") == 0,
           f"every fixture lava tile has four present neighbours: "
           f"LAVA_RIM_INCOMPLETE "
           f"{count_category(result, 'LAVA_RIM_INCOMPLETE')}, expected 0")

    # WHY that zero holds, stated as an assertion rather than a comment:
    # every dry rim tile sits EXACTLY at the pool surface, which is what
    # poolRimCaps writes. A count of zero with no dry rim at all would be
    # vacuous; this shows the rim is really there and really flush.
    rim: list[tuple[tuple[int, int], tuple[int, int]]] = []
    off_surface = []
    for t in lava:
        for nbr in neighbors4(t["x"], t["y"]):
            n = grid.get(nbr)
            if n is None or n["fluidType"] is not None:
                continue
            rim.append((nbr, (t["x"], t["y"])))
            if n["terrainZ"] != t["fluidSurf"]:
                off_surface.append((nbr, n["terrainZ"], t["fluidSurf"]))
    expect(len(rim) == 36,
           f"the pool really has a dry rim to judge: {len(rim)} rim "
           f"adjacencies, expected 36")
    expect(not off_surface,
           f"every dry rim tile is flush with the lava surface "
           f"(poolRimCaps): off-surface {off_surface[:5]}")

    # Mutation 1 — undo one real tile's cap. This is what the rim looked
    # like before poolRimCaps raised it, and what a regression in that
    # sealing pass would leave behind.
    rim.sort()
    (rx, ry), (lx, ly) = rim[0]
    mutated = [dict(t) for t in data]
    for t in mutated:
        if (t["x"], t["y"]) == (rx, ry):
            t["terrainZ"] -= 1
            t["surfaceZ"] = t["terrainZ"]
    result = audit_dump(mutated).to_dict()
    expect(issue_coords(result, "LAVA_RIM_BREACH") == [(lx, ly)],
           f"lowering the real rim tile {(rx, ry)} by one z breaches the "
           f"lava tile beside it: {issue_coords(result, 'LAVA_RIM_BREACH')}, "
           f"expected [{(lx, ly)}]")

    # Mutation 2 — drop one real cardinal neighbour out of the window, the
    # way a dump region boundary would cut it.
    trimmed = [t for t in data if (t["x"], t["y"]) != (rx, ry)]
    result = audit_dump(trimmed).to_dict()
    expect((lx, ly) in issue_coords(result, "LAVA_RIM_INCOMPLETE"),
           f"a real lava tile whose neighbour left the window records an "
           f"incomplete judgement: "
           f"{issue_coords(result, 'LAVA_RIM_INCOMPLETE')}, expected to "
           f"contain {(lx, ly)}")
    expect(count_category(result, "LAVA_RIM_BREACH") == 0,
           f"and still reports no breach: LAVA_RIM_BREACH "
           f"{count_category(result, 'LAVA_RIM_BREACH')}, expected 0")


def test_terrain_spike() -> None:
    print("test_terrain_spike")
    # Flat terrain with one tile spike
    tiles = flat_grid(5, 5, -2, -2, terrainZ=1, fluidType=None)
    # Replace center with a spike
    tiles = make_tiles(tiles)
    for i, t in enumerate(tiles):
        if t["x"] == 0 and t["y"] == 0:
            tiles[i] = tile(0, 0, terrainZ=100)
            break
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "TERRAIN_SPIKE") == 1,
           f"TERRAIN_SPIKE count: {count_category(result, 'TERRAIN_SPIKE')}, expected 1")


def test_terrain_pit() -> None:
    print("test_terrain_pit")
    tiles = flat_grid(5, 5, -2, -2, terrainZ=100, fluidType=None)
    tiles = make_tiles(tiles)
    for i, t in enumerate(tiles):
        if t["x"] == 0 and t["y"] == 0:
            tiles[i] = tile(0, 0, terrainZ=1)
            break
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "TERRAIN_PIT") == 1,
           f"TERRAIN_PIT count: {count_category(result, 'TERRAIN_PIT')}, expected 1")


def test_terrain_pit_submerged() -> None:
    print("test_terrain_pit_submerged")
    # A deep hole under a lake whose surface covers the lowest
    # neighbour: the water plane renders flat over it — concealed,
    # not an artifact. The despike pass only lowers, never raises,
    # so these are legitimate worldgen output.
    tiles = flat_grid(5, 5, -2, -2, terrainZ=100, fluidType=None)
    tiles = make_tiles(tiles)
    for i, t in enumerate(tiles):
        if t["x"] == 0 and t["y"] == 0:
            tiles[i] = tile(0, 0, terrainZ=1, fluidType="lake", fluidSurf=100)
            break
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "TERRAIN_PIT") == 0,
           f"submerged pit: TERRAIN_PIT count "
           f"{count_category(result, 'TERRAIN_PIT')}, expected 0 (concealed)")
    # But a pit whose fluid does NOT reach the lowest neighbour is
    # still a visible wall — must flag.
    for i, t in enumerate(tiles):
        if t["x"] == 0 and t["y"] == 0:
            tiles[i] = tile(0, 0, terrainZ=1, fluidType="lake", fluidSurf=3)
            break
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "TERRAIN_PIT") == 1,
           f"shallow-puddle pit: TERRAIN_PIT count "
           f"{count_category(result, 'TERRAIN_PIT')}, expected 1 (visible)")


def test_terrain_spike_submerged() -> None:
    print("test_terrain_spike_submerged")
    # An ocean seamount: spike fully under its own fluid surface
    # renders as flat water — concealed. (Real case: basalt seamount
    # from an underwater vent, seed 4 w64.)
    tiles = flat_grid(5, 5, -2, -2, terrainZ=-50, fluidType="ocean",
                      fluidSurf=0)
    tiles = make_tiles(tiles)
    for i, t in enumerate(tiles):
        if t["x"] == 0 and t["y"] == 0:
            tiles[i] = tile(0, 0, terrainZ=-20, fluidType="ocean", fluidSurf=0)
            break
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "TERRAIN_SPIKE") == 0,
           f"submerged spike: TERRAIN_SPIKE count "
           f"{count_category(result, 'TERRAIN_SPIKE')}, expected 0 (concealed)")
    # A dry spike poking above the surrounding water is an island /
    # pillar — still flags.
    for i, t in enumerate(tiles):
        if t["x"] == 0 and t["y"] == 0:
            tiles[i] = tile(0, 0, terrainZ=5, fluidType=None)
            break
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "TERRAIN_SPIKE") == 1,
           f"emergent spike: TERRAIN_SPIKE count "
           f"{count_category(result, 'TERRAIN_SPIKE')}, expected 1 (visible)")


def test_river_chunk_gap() -> None:
    print("test_river_chunk_gap")
    # River at x=15 (chunk edge), dry at x=16 (next chunk), terrain low
    tiles = [
        tile(15, 0, terrainZ=2, fluidType="river", fluidSurf=5),
        tile(16, 0, terrainZ=2, fluidType=None),
    ]
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "RIVER_CHUNK_GAP") == 1,
           f"RIVER_CHUNK_GAP count: {count_category(result, 'RIVER_CHUNK_GAP')}, expected 1")


def test_river_mouth_drop() -> None:
    print("test_river_mouth_drop")
    tiles = [
        tile(0, 0, terrainZ=5, fluidType="river", fluidSurf=15),
        tile(1, 0, terrainZ=-5, fluidType="ocean", fluidSurf=0),
    ]
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "RIVER_MOUTH_DROP") == 1,
           f"RIVER_MOUTH_DROP count: {count_category(result, 'RIVER_MOUTH_DROP')}, expected 1")


def test_island_1tile() -> None:
    print("test_island_1tile")
    # 1 dry tile surrounded by ocean
    tiles = [
        tile(-1, 0, terrainZ=-1, fluidType="ocean", fluidSurf=0),
        tile(1, 0, terrainZ=-1, fluidType="ocean", fluidSurf=0),
        tile(0, -1, terrainZ=-1, fluidType="ocean", fluidSurf=0),
        tile(0, 1, terrainZ=-1, fluidType="ocean", fluidSurf=0),
        tile(0, 0, terrainZ=-1, fluidType=None),
    ]
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "ISLAND_1TILE") == 1,
           f"ISLAND_1TILE count: {count_category(result, 'ISLAND_1TILE')}, expected 1")


def test_isolated_fluid() -> None:
    print("test_isolated_fluid")
    # 1 river tile surrounded by dry
    tiles = [
        tile(-1, 0, terrainZ=10, fluidType=None),
        tile(1, 0, terrainZ=10, fluidType=None),
        tile(0, -1, terrainZ=10, fluidType=None),
        tile(0, 1, terrainZ=10, fluidType=None),
        tile(0, 0, terrainZ=5, fluidType="river", fluidSurf=8),
    ]
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "ISOLATED_FLUID") == 1,
           f"ISOLATED_FLUID count: {count_category(result, 'ISOLATED_FLUID')}, expected 1")


def test_minbound_leak() -> None:
    print("test_minbound_leak")
    tiles = [
        tile(0, 0, terrainZ=INT64_MIN),  # beyondGlacier=False
    ]
    # Override surfaceZ since our helper doesn't handle minBound right
    tiles[0]["surfaceZ"] = INT64_MIN
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "MINBOUND_LEAK") == 1,
           f"MINBOUND_LEAK count: {count_category(result, 'MINBOUND_LEAK')}, expected 1")


def test_surface_inconsistent() -> None:
    print("test_surface_inconsistent")
    tiles = [
        {"x": 0, "y": 0, "v": 0,
         "terrainZ": 10, "surfaceZ": 5,  # wrong: should be max(10, None) = 10
         "matId": 64,
         "fluidType": None, "fluidSurf": None,
         "iceSurf": None, "iceMode": None,
         "glacierZone": False, "beyondGlacier": False},
    ]
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "SURFACE_INCONSISTENT") == 1,
           f"SURFACE_INCONSISTENT count: {count_category(result, 'SURFACE_INCONSISTENT')}, expected 1")


def test_river_surface_uses_fluid_not_max() -> None:
    """River tiles render surfaceZ = fluidSurf (not max(terr, fluid))
    because the engine hides terrain protrusions under the water plane.
    A river tile with surfaceZ = terrainZ when fluidSurf < terrainZ is
    INCONSISTENT (engine writes fluidSurf), and surfaceZ = fluidSurf is
    correct even though terrain pokes above."""
    print("test_river_surface_uses_fluid_not_max")
    # Correct: river with terr=10, water=8, surface=8 (water plane, NOT max).
    correct = [{
        "x": 0, "y": 0, "v": 0,
        "terrainZ": 10, "surfaceZ": 8,
        "matId": 64,
        "fluidType": "river", "fluidSurf": 8,
        "iceSurf": None, "iceMode": None,
        "glacierZone": False, "beyondGlacier": False,
    }]
    r = audit_dump(correct).to_dict()
    expect(count_category(r, "SURFACE_INCONSISTENT") == 0,
           f"river surface = fluidSurf should be consistent, "
           f"got {count_category(r, 'SURFACE_INCONSISTENT')}")

    # Incorrect: river where surfaceZ == max(terr, fluid). The engine
    # never writes this for River, so it indicates a real bug.
    wrong = [{
        "x": 0, "y": 0, "v": 0,
        "terrainZ": 10, "surfaceZ": 10,  # should be 8
        "matId": 64,
        "fluidType": "river", "fluidSurf": 8,
        "iceSurf": None, "iceMode": None,
        "glacierZone": False, "beyondGlacier": False,
    }]
    r = audit_dump(wrong).to_dict()
    expect(count_category(r, "SURFACE_INCONSISTENT") == 1,
           f"river with surface=max(terr,fluid) should flag, "
           f"got {count_category(r, 'SURFACE_INCONSISTENT')}")


def test_lake_surface_uses_max() -> None:
    """Lake/ocean/lava still use max(terrainZ, fluidSurf) — only rivers
    have the special flat rule."""
    print("test_lake_surface_uses_max")
    # Lake with terr=5, water=8, surface=8 (max) — correct
    tiles = [{
        "x": 0, "y": 0, "v": 0,
        "terrainZ": 5, "surfaceZ": 8,
        "matId": 64,
        "fluidType": "lake", "fluidSurf": 8,
        "iceSurf": None, "iceMode": None,
        "glacierZone": False, "beyondGlacier": False,
    }]
    r = audit_dump(tiles).to_dict()
    expect(count_category(r, "SURFACE_INCONSISTENT") == 0,
           f"lake surface = max(terr, fluid) should be consistent, "
           f"got {count_category(r, 'SURFACE_INCONSISTENT')}")


def test_dry_below_sea_inland_basin() -> None:
    """An inland basin below sea level that is NOT connected to the
    ocean (e.g. a sub-sea-level cave system or a closed depression)
    should not flag DRY_BELOW_SEA — those dry tiles are legitimate."""
    print("test_dry_below_sea_inland_basin")
    # Surround a sub-sea region with above-sea-level terrain — there's
    # no ocean path to the inner dry tile, so it should not flag.
    tiles = []
    for y in range(-3, 4):
        for x in range(-3, 4):
            # Outer ring above sea level
            if abs(x) == 3 or abs(y) == 3:
                tiles.append(tile(x, y, terrainZ=20))
            else:
                # Inner region below sea level, all dry
                tiles.append(tile(x, y, terrainZ=-5))
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "DRY_BELOW_SEA") == 0,
           f"inland basin should not flag DRY_BELOW_SEA, "
           f"got {count_category(result, 'DRY_BELOW_SEA')}")


def test_dry_below_sea_ocean_connected() -> None:
    """A dry tile directly adjacent to ocean tiles IS a bug and must
    flag — the ocean has clearly not reached a tile it should have."""
    print("test_dry_below_sea_ocean_connected")
    tiles = []
    # 5x5 ocean region
    for y in range(-2, 3):
        for x in range(-2, 3):
            tiles.append(tile(x, y, terrainZ=-3,
                              fluidType="ocean", fluidSurf=0))
    # Convert one to dry
    for i, t in enumerate(tiles):
        if t["x"] == 0 and t["y"] == 0:
            tiles[i] = tile(0, 0, terrainZ=-3, fluidType=None)
            break
    result = audit_dump(tiles).to_dict()
    expect(count_category(result, "DRY_BELOW_SEA") == 1,
           f"ocean-connected dry tile should flag, "
           f"got {count_category(result, 'DRY_BELOW_SEA')}")


def test_wetland_on_slope() -> None:
    """Wetland soil with ANY 4-neighbour delta > 2 is a BUG (the gate
    is border-aware since 2026-06-07, so cross-chunk counts too);
    flat wetland and submerged bed material are not."""
    print("test_wetland_on_slope")
    # Flat wetland: clean. Coords 1..5 stay inside chunk 0.
    tiles = [tile(x, y, terrainZ=10, matId=64)
             for y in range(1, 6) for x in range(1, 6)]
    r = audit_dump(make_tiles(tiles)).to_dict()
    expect(count_category(r, "WETLAND_ON_SLOPE") == 0,
           f"flat wetland should be clean, got "
           f"{count_category(r, 'WETLAND_ON_SLOPE')}")

    # Raise the centre tile (non-wetland) by 5: its 4 wetland
    # neighbours each see delta 5 > 2.
    spiked = make_tiles(tiles + [tile(3, 3, terrainZ=15, matId=56)])
    r = audit_dump(spiked).to_dict()
    expect(count_category(r, "WETLAND_ON_SLOPE") == 4,
           f"4 wetland neighbours of the spike should flag, got "
           f"{count_category(r, 'WETLAND_ON_SLOPE')}")

    # Cross-chunk delta now FLAGS: wetland at x=15 (chunk 0) next to
    # a +5 cliff at x=16 (chunk 1) — wetlandKeep reads the bordered
    # post-carve vector, so border tiles are gated like interior ones.
    border = make_tiles([
        tile(15, 3, terrainZ=10, matId=64),
        tile(16, 3, terrainZ=15, matId=56),
        tile(14, 3, terrainZ=10, matId=56),
        tile(15, 2, terrainZ=10, matId=56),
        tile(15, 4, terrainZ=10, matId=56),
    ])
    r = audit_dump(border).to_dict()
    expect(count_category(r, "WETLAND_ON_SLOPE") == 1,
           f"cross-chunk delta should flag (border-aware gate), got "
           f"{count_category(r, 'WETLAND_ON_SLOPE')}")

    # Submerged bed material is concealed by the water plane — a
    # steep lake-bed pillar wearing muck must NOT flag.
    sub = make_tiles(
        [tile(x, y, terrainZ=1, matId=50, fluidType="lake", fluidSurf=12)
         for y in range(1, 6) for x in range(1, 6)]
        + [tile(3, 3, terrainZ=10, matId=64, fluidType="lake",
                fluidSurf=12)])
    r = audit_dump(sub).to_dict()
    expect(count_category(r, "WETLAND_ON_SLOPE") == 0,
           f"submerged steep wetland should be exempt, got "
           f"{count_category(r, 'WETLAND_ON_SLOPE')}")


def test_desert_soil_on_slope() -> None:
    """Sand / salt flat on a same-chunk slope is a QUALITY issue."""
    print("test_desert_soil_on_slope")
    # Flat sand: clean.
    tiles = [tile(x, y, terrainZ=10, matId=55)
             for y in range(1, 6) for x in range(1, 6)]
    r = audit_dump(make_tiles(tiles)).to_dict()
    expect(count_category(r, "DESERT_SOIL_ON_SLOPE") == 0,
           f"flat sand should be clean, got "
           f"{count_category(r, 'DESERT_SOIL_ON_SLOPE')}")

    # Spike beside sand and a salt flat: both neighbours flag.
    spiked = make_tiles(tiles + [
        tile(3, 3, terrainZ=15, matId=56),
        tile(2, 3, terrainZ=10, matId=67),  # salt flat next to spike
    ])
    r = audit_dump(spiked).to_dict()
    expect(count_category(r, "DESERT_SOIL_ON_SLOPE") == 4,
           f"3 sand + 1 salt-flat neighbours should flag, got "
           f"{count_category(r, 'DESERT_SOIL_ON_SLOPE')}")


def test_clean_grid() -> None:
    """A clean grid with no issues should return zero bugs."""
    print("test_clean_grid")
    # All ocean below sea level, no issues
    tiles = flat_grid(5, 5, -2, -2, terrainZ=-5, fluidType="ocean", fluidSurf=0)
    result = audit_dump(tiles).to_dict()
    total = sum(result["summary"].values())
    expect(total == 0, f"clean grid should have 0 issues, got {total}: {result['summary']}")


def test_stats() -> None:
    """Fluid stats and elevation stats should be computed correctly."""
    print("test_stats")
    tiles = (
        flat_grid(3, 3, 0, 0, terrainZ=10, fluidType=None) +
        flat_grid(3, 3, 10, 0, terrainZ=-5, fluidType="ocean", fluidSurf=0) +
        flat_grid(3, 3, 20, 0, terrainZ=5, fluidType="river", fluidSurf=8)
    )
    result = audit_dump(tiles)
    d = result.to_dict()
    expect(d["tileCount"] == 27, f"tileCount: {d['tileCount']}, expected 27")
    expect(d["fluidStats"]["dry"] == 9, f"fluidStats.dry: {d['fluidStats']}")
    expect(d["fluidStats"]["ocean"] == 9, f"fluidStats.ocean: {d['fluidStats']}")
    expect(d["fluidStats"]["river"] == 9, f"fluidStats.river: {d['fluidStats']}")
    expect(d["elevationStats"]["min"] == -5, f"min: {d['elevationStats']}")
    expect(d["elevationStats"]["max"] == 10, f"max: {d['elevationStats']}")


def test_issue_ordering_is_canonical() -> None:
    """Serialized audit output is canonical in its ISSUE ORDER.

    `AuditResult.to_dict` sorts issues by (category, x, y) before grouping
    them. That sort is what makes an audit's issue arrays comparable
    between runs and keeps a re-captured baseline file's diff stable;
    `json.dumps(sort_keys=True)` cannot stand in for it, because it orders
    an object's KEYS and leaves its arrays exactly as built. Nothing else
    in this suite pins it: every per-category fixture asserts through
    `count_category`, which counts issues without looking at their order.

    Feeding ONE fixture through `audit_dump` in two different input orders
    and requiring byte-identical serializations tests exactly that. A
    same-input comparison cannot: `audit_dump` builds fresh state from its
    argument and reads no clock, randomness, or retained cross-call state,
    so two identical calls are equal however the sort is written — or
    whether it is written at all.

    LIMITATION, and why this fixture is built the way it is: the
    (category, x, y) key is not total. Two issues sharing all three and
    differing only in `details` keep their append order under Python's
    stable `sorted`, and append order follows the input list, so such a
    pair would make this test fail legitimately rather than reveal a
    regression. The fixture below therefore uses coordinates that are
    DISTINCT within each category, which the guards ahead of the
    comparison assert rather than assume; any fixture substituted here
    must hold the same property.
    """
    print("test_issue_ordering_is_canonical")
    # Two coordinate-disjoint clusters, each flagging four issues in one
    # category: wetland soil (matId 64) around a +5 spike in chunk 0, and
    # sand / salt flat (matId 55 / 67) around a second spike in chunk 1.
    wetland = [tile(x, y, terrainZ=10, matId=64)
               for y in range(1, 6) for x in range(1, 6)]
    wetland.append(tile(3, 3, terrainZ=15, matId=56))
    desert = [tile(x, y, terrainZ=10, matId=55)
              for y in range(1, 6) for x in range(17, 22)]
    desert.append(tile(19, 3, terrainZ=15, matId=56))
    desert.append(tile(18, 3, terrainZ=10, matId=67))

    # Normalize BEFORE permuting. `audit_dump` builds its grid with
    # last-write-wins duplicate-coordinate semantics, so reversing a list
    # still holding unresolved duplicates would change the INPUT, not just
    # its order, and the two runs would no longer be permutations.
    forward = make_tiles(wetland + desert)
    reverse = list(reversed(forward))

    result = audit_dump(forward)
    triples = [(i.category, i.x, i.y) for i in result.issues]
    per_category: dict[str, int] = {}
    for category, _x, _y in triples:
        per_category[category] = per_category.get(category, 0) + 1

    # Guards: without them a fixture that drifted to one issue, or to one
    # issue per category, would keep passing while pinning nothing —
    # sorting a singleton array is a no-op, so removing the sort would
    # stay invisible.
    expect(len(per_category) >= 2,
           f"fixture must produce at least two categories, got "
           f"{sorted(per_category)}")
    expect(any(n > 1 for n in per_category.values()),
           f"fixture must produce a category holding several issues, got "
           f"{per_category}")
    expect(len(triples) == len(set(triples)),
           f"fixture must not repeat a (category, x, y) triple — the sort "
           f"key is not total, so duplicates would order by append: "
           f"{sorted(triples)}")

    forward_json = json.dumps(result.to_dict(), sort_keys=True)
    reverse_json = json.dumps(audit_dump(reverse).to_dict(), sort_keys=True)
    expect(forward_json == reverse_json,
           "audit output is not canonical under input reordering: the same "
           "tiles fed in reverse serialized differently, so to_dict's "
           "(category, x, y) issue sort is missing or weakened")



#: The order `world_audit.ALL_CHECKS` has always run its checks in, held
#: here as a literal. Requirement 16 of #2224 pins it because the tracked
#: baselines and the real-output fixture were captured against runs in
#: this order; reading it back from `world_audit.CHECK_ORDER` would make
#: the assertion below tautological.
HISTORICAL_CHECK_ORDER = [
    "DRY_BELOW_SEA",
    "OCEAN_ON_LAND",
    "RIVER_UNDER_TERRAIN",
    "FLOATING_FLUID",
    "LAVA_RIM_CONTAINMENT",
    "TERRAIN_SPIKES_PITS",
    "RIVER_CHUNK_GAP",
    "RIVER_MOUTH_DROP",
    "ISLAND_1TILE",
    "LAKE_HOLE",
    "SUBMERGED_BUMP",
    "WATER_ABOVE_LAND",
    "WATER_CLIFF",
    "WATER_WATER_CLIFF",
    "MID_RIVER_CLIFF",
    "FLOATING_WATER",
    "MULTI_ISLAND",
    "FLAT_ISOLATED_WATER",
    "ISOLATED_FLUID",
    "MINBOUND_LEAK",
    "SURFACE_INCONSISTENT",
    "WETLAND_ON_SLOPE",
    "DESERT_SOIL_ON_SLOPE",
]


def _owner(name: str, checks: dict[str, Any] | None) -> types.SimpleNamespace:
    """A stand-in check owner: a module-shaped object with a CHECKS map.

    `compose_checks` reads an owner through `getattr(module, "CHECKS")`
    and names it by `__name__`, so a namespace is a faithful stand-in and
    no real owner has to be mutated to drive a refusal.
    """
    owner = types.SimpleNamespace()
    owner.__name__ = f"fake_{name}"
    if checks is not None:
        owner.CHECKS = checks
    return owner


def test_registry_composition_fails_closed() -> None:
    """ALL_CHECKS is composed from the owners' inventories and refuses any
    arrangement that would run a shortened audit (#2224).

    The registry is production code, and every refusal below is a way the
    audit could silently stop running a check while still reporting a
    green run: an owner gone or emptied, a key two owners both claim, one
    function reached under two keys, an ordered key nobody owns, an order
    that repeats a key, and an owner-declared check the order drops."""
    print("test_registry_composition_fails_closed")

    def one(grid: Any, issues: Any) -> None:
        pass

    def two(grid: Any, issues: Any) -> None:
        pass

    def three(grid: Any, issues: Any) -> None:
        pass

    def four(grid: Any, issues: Any) -> None:
        pass

    healthy = {
        "columns": _owner("columns", {"A": one}),
        "boundaries": _owner("boundaries", {"B": two}),
        "regions": _owner("regions", {"C": three}),
        "soils": _owner("soils", {"D": four}),
    }

    def refuses(label: str, owners: dict[str, Any], order: tuple[str, ...],
                names: str) -> None:
        """Compose and require a RegistryError whose message names the cause."""
        try:
            world_audit.compose_checks(owners, order)
        except world_audit.RegistryError as error:
            expect(names in str(error),
                   f"{label}: the refusal must name {names!r}, got "
                   f"{str(error)!r}")
        else:
            expect(False,
                   f"{label}: composed without refusing — a shortened audit "
                   f"would report a green run")

    order = ("A", "B", "C", "D")

    # The healthy arrangement composes, in the order given rather than the
    # order the owners are visited in.
    composed = world_audit.compose_checks(healthy, ("D", "B", "C", "A"))
    expect(list(composed) == ["D", "B", "C", "A"],
           f"compose_checks must follow the given order, got {list(composed)}")
    expect(composed == {"A": one, "B": two, "C": three, "D": four},
           f"compose_checks must bind each key to its owner's check, got "
           f"{composed}")

    missing_owner = dict(healthy)
    del missing_owner["soils"]
    refuses("an absent owner", missing_owner, order, "'soils'")

    no_inventory = dict(healthy, soils=_owner("soils", None))
    refuses("an owner that declares no CHECKS", no_inventory, order,
            "declares no CHECKS")

    emptied = dict(healthy, soils=_owner("soils", {}))
    refuses("an emptied owner", emptied, order, "empty CHECKS")

    shared_key = dict(healthy, soils=_owner("soils", {"A": four}))
    refuses("a key two owners declare", shared_key, order, "'A'")

    shared_fn = dict(healthy, soils=_owner("soils", {"D": one}))
    refuses("one function under two keys", shared_fn, order, "both register")

    refuses("an ordered key no owner declares", healthy,
            order + ("UNOWNED",), "'UNOWNED'")

    refuses("an order that repeats a key", healthy, order + ("A",),
            "more than once")

    refuses("an owner-declared check the order drops", healthy, ("A", "B", "C"),
            "soils:D")

    # The live registry is that composition, not a hand-written dict.
    expect(world_audit.ALL_CHECKS == world_audit.compose_checks(),
           "ALL_CHECKS must be exactly what compose_checks() returns")

    # The historical run order, restated here rather than read from
    # CHECK_ORDER: baselines and the tracked real-output fixture were
    # captured against it, so holding the registry against the production
    # constant that defines it would pin nothing.
    expect(list(world_audit.ALL_CHECKS) == HISTORICAL_CHECK_ORDER,
           f"ALL_CHECKS no longer runs in the order the tracked baselines "
           f"were captured in: {list(world_audit.ALL_CHECKS)}")
    expect(len(set(world_audit.ALL_CHECKS.values())) == 23,
           f"the 23 registry keys must reach 23 distinct check functions, "
           f"got {len(set(world_audit.ALL_CHECKS.values()))}")

    # And audit_dump runs each registered check exactly once. Counting
    # wrappers stand in for the registry for one call; the original dict
    # object is restored and re-checked, because a self-test that leaves a
    # production global swapped would corrupt every group after it.
    original = world_audit.ALL_CHECKS
    calls: dict[str, int] = {key: 0 for key in original}

    def counter(key: str, check_fn: Any) -> Any:
        def wrapped(grid: Any, issues: Any) -> None:
            calls[key] += 1
            check_fn(grid, issues)
        return wrapped

    try:
        world_audit.ALL_CHECKS = {key: counter(key, fn)
                                  for key, fn in original.items()}
        audit_dump(make_tiles(flat_grid(3, 3)))
    finally:
        world_audit.ALL_CHECKS = original

    expect(world_audit.ALL_CHECKS is original,
           "the registry global must be restored after the counting run")
    off = {key: n for key, n in calls.items() if n != 1}
    expect(not off,
           f"audit_dump must run every registered check exactly once, got "
           f"{off}")


#: This owner's inventory, in two fragments. The aggregate has always
#: run the two emitted-category groups (owned by
#: `test_audit_categories`) INSIDE the audit block, between these
#: leading groups and the two trailing slope checks; exposing the
#: seam lets `tools/test_audit.py` keep that position without
#: knowing any group by name. `TESTS` is the complete inventory the
#: façade accounts against.
TESTS_LEADING = (
    test_clean_grid,
    test_stats,
    test_issue_ordering_is_canonical,
    test_dry_below_sea,
    test_ocean_on_land,
    test_river_under_terrain,
    test_lake_under_terrain,
    test_floating_fluid,
    test_lava_rim_containment,
    test_lava_rim_on_real_generated_output,
    test_terrain_spike,
    test_terrain_pit,
    test_terrain_pit_submerged,
    test_terrain_spike_submerged,
    test_river_chunk_gap,
    test_river_mouth_drop,
    test_island_1tile,
    test_isolated_fluid,
    test_minbound_leak,
    test_surface_inconsistent,
    test_river_surface_uses_fluid_not_max,
    test_lake_surface_uses_max,
    test_dry_below_sea_inland_basin,
    test_dry_below_sea_ocean_connected,
)

TESTS_TRAILING = (
    test_wetland_on_slope,
    test_desert_soil_on_slope,
    test_registry_composition_fails_closed,
)

TESTS = TESTS_LEADING + TESTS_TRAILING
