{-# LANGUAGE CPP, UnicodeSyntax #-}
module Engine.Loop.Frame
  ( drawFrame
  , updateUniformBufferForFrame
  , submitFrame
  , computeAmbientLight
  , activeWorldCircumferenceTiles
  ) where

import UPrelude
import Control.Exception (displayException)
import qualified Data.Text as T
import qualified Data.Vector as V
import qualified Data.Vector.Storable as VS
import qualified Data.Map as Map
import Data.IORef (readIORef, writeIORef)
import Linear (identity)
import Engine.Core.Defaults
import Engine.Core.Log (LogCategory(..))
import Engine.Core.Log.Monad (logInfoM, logAndThrowM)
import Engine.Core.Monad
import Engine.Core.State
import Engine.Core.Error.Exception (ExceptionType(..), GraphicsError(..)
                                   , SystemError(..))
import Engine.Graphics.Base
import Engine.Graphics.Camera
import Engine.Graphics.Config (brightnessToMultiplier)
import Engine.Graphics.Window.Types (Window(..))
import Engine.Graphics.Types (DevQueues(..))
import qualified Engine.Graphics.Window.GLFW as GLFW
import Engine.Graphics.Vulkan.Buffer
import Engine.Graphics.Vulkan.Command
import Engine.Graphics.Vulkan.Recreate (recreateSwapchain)
import Engine.Graphics.Vulkan.Types
import Engine.Loop.Resource (validateDescriptorState, getFrameResources, 
                              getCommandBuffer, getDevice, getSwapchain,
                              getQueues, extractWindow)
import Engine.Scene.Render
import Engine.Scene.Types
import UI.Render (renderUIPages)
import UI.Tooltip (updateTooltipState)
import World.Types (chunkSize, WorldGenParams(..), WorldState(..))
import Vulkan.Core10
import Vulkan.Zero
import Vulkan.CStruct.Extends
import Vulkan.Extensions.VK_KHR_swapchain hiding (acquireNextImageKHRSafe)

computeAmbientLight ∷ Float → Float
computeAmbientLight sunAngle =
    let angle = sunAngle * 2.0 * π
        sunHeight = sin angle
    in if sunHeight ≥ 0
       then 0.5 + 0.2 * sunHeight   -- day: 0.5 at horizon, 0.7 at noon
       else 0.15 + 0.35 * (1.0 + sunHeight)  -- night: 0.15 at midnight, 0.5 at horizon

-- | The active world's u-axis (gx-gy) circumference in tiles, for the
--   world vertex shader's per-vertex longitude-local day/night phase
--   (#483). Falls back to a 128-chunk world (the same default
--   'World.Render.Quads' uses when gen params aren't loaded yet) —
--   there's always SOME UBO value even before a world finishes
--   generating, since the shader divides by it.
activeWorldCircumferenceTiles ∷ EngineEnv → IO Float
activeWorldCircumferenceTiles env = do
    mWs ← activeWorldState env
    mParams ← case mWs of
        Just ws → readIORef (wsGenParamsRef ws)
        Nothing → pure Nothing
    let worldSize = maybe 128 wgpWorldSize mParams
    pure (fromIntegral (worldSize * chunkSize))

-- | Draw a single frame
drawFrame ∷ EngineM ε σ ()
drawFrame = do
    state ← gets graphicsState
    
    -- Get window
    window@(Window win) ← case extractWindow state of
        Left err → logAndThrowM CatSystem
          (ExSystem (GLFWError "drawFrame: ")) $ T.pack $
            "No window: " ⧺ displayException err
        Right w → pure w
    
    let frameIdx = currentFrame state
    
    -- Get frame resources and device early
    resources ← getFrameResources state frameIdx
    device ← getDevice state
    
    -- Wait for this frame's previous work to complete. Result discard is
    -- safe: timeout is maxBound, so non-SUCCESS throws as VulkanException.
    _ ← liftIO $ waitForFences device (V.singleton (frInFlight resources)) True maxBound

    -- Try to acquire image BEFORE resetting fence
    swapchain ← getSwapchain state
    acquireResult ← liftIO $ acquireNextImageKHRSafe device swapchain maxBound
                                 (frImageAvailable resources) zero
    
    case acquireResult of
        Left ERROR_OUT_OF_DATE_KHR → do
            logInfoM CatGraphics "Swapchain out of date on acquire, recreating..."
            recreateSwapchain window
        
        Left err → logAndThrowM CatGraphics
          (ExGraphics SwapchainError) $ T.pack $
            "Failed to acquire swapchain image: " ⧺ show err
        
        Right imageIndex → do
            
            -- NOW reset fence since we're definitely going to submit
            liftIO $ resetFences device (V.singleton (frInFlight resources))

            -- 1. Collect world quads (pre-generated by world thread):
            --    static terrain arrives pre-grouped by layer and
            --    pre-sorted (built at quad-cache rebuild); only the
            --    small dynamic rest needs per-frame sorting (#446).
            env ← ask
            worldQuads ← liftIO $ readIORef (worldQuadsRef env)

            -- Read the LIVE camera for the view matrix.
            -- Previously we used worldCamera from the world thread,
            -- which could be tens of milliseconds stale during chunk
            -- generation. This caused the viewport to jerk because
            -- the view matrix lagged behind the actual camera position
            -- that the main thread was updating every frame.
            liveCamera ← liftIO $ readIORef (cameraRef env)

            -- 2. Update scene (populates BatchManager with DrawableObjects)
            updateSceneForRender
            _sceneMgr ← gets sceneManager

            -- 3. Get scene sprites in world layers as SortableQuads
            sceneQuads ← getWorldSceneQuads

            -- 4. Sort the dynamic quads (units, cursor, ghost, scene
            --    sprites — small) per layer, then linear-merge them into
            --    the cached pre-sorted static runs. Static sits on the
            --    left of the merge, so a dynamic sprite at exactly a
            --    tile's depth deterministically draws over it.
            let dynByLayer = sortQuadsByLayer
                    (lqDynamic worldQuads <> sceneQuads)
                groupedByLayer = Map.unionWith mergeSortedQuads
                    (lqStatic worldQuads) dynByLayer
                perLayerBatches = Map.mapWithKey batchFromSortedQuads groupedByLayer
                worldLayeredBatches = Map.map
                    (\batch → V.singleton (SpriteItem batch))
                    perLayerBatches
            
            -- 5. Tick tooltip subsystem (resolves hover, builds/destroys
            --    the transient tooltip page on LayerTooltip). Must run
            --    BEFORE renderUIPages so this frame's UI pass picks up
            --    the tooltip elements.
            updateTooltipState

            -- 6. Render UI
            (_uiBatches, uiLayeredBatches) ← renderUIPages
            
            -- 7. Final merge: world + UI
            let layeredBatches = Map.unionsWith (<>)
                    [worldLayeredBatches, uiLayeredBatches]

                -- Build sprite batches in layer-ascending order so the
                -- vertex buffer layout matches the draw-call order in
                -- recordSceneCommandBuffer.  Previously we used
                -- worldBatches <> uiBatches which is per-page order;
                -- when multiple visible pages shared layer IDs the
                -- vertexOffsetRef tracking got out of sync.
                batches = V.concatMap
                    (V.mapMaybe (\case SpriteItem b → Just b; _ → Nothing))
                    (V.fromList $ map snd $ Map.toAscList layeredBatches)

            -- Use the LIVE camera for the view/projection matrices
            updateUniformBufferForFrame win frameIdx liveCamera

            -- Prepare dynamic vertex buffer
            let totalVertices = V.sum $ V.map (fromIntegral . VS.length . rbVertices) batches

            dynamicBuffer ← if totalVertices > 0
                then do
                    buffer ← ensureDynamicVertexBuffer (fromIntegral frameIdx) totalVertices
                    uploadBatchesToBuffer (fromIntegral frameIdx) batches buffer
                else ensureDynamicVertexBuffer (fromIntegral frameIdx) 6
            
            -- Validate resources
            state'' ← gets graphicsState
            validateDescriptorState state''
            
            -- Record command buffer
            cmdBuffer ← getCommandBuffer resources
            liftIO $ resetCommandBuffer cmdBuffer zero
            recordSceneCommandBuffer cmdBuffer (fromIntegral imageIndex)
                                     (fromIntegral frameIdx)
                                     dynamicBuffer layeredBatches
            
            -- Submit + present both use the per-IMAGE render-finished
            -- semaphore (the image count can differ from frames in flight,
            -- so it can't live in the per-frame FrameResources).
            queues ← getQueues state''
            let rfSems = renderFinishedSems state''
            renderFinishedSem ← if fromIntegral imageIndex < V.length rfSems
                then pure (rfSems V.! fromIntegral imageIndex)
                else logAndThrowM CatGraphics (ExGraphics SwapchainError)
                       "imageIndex out of renderFinished semaphore bounds"
            submitFrame cmdBuffer resources queues renderFinishedSem

            -- Present - get fresh swapchain from state
            currentState ← gets graphicsState
            currentSwapchain ← getSwapchain currentState
            presentResult ← presentFrameWithResult renderFinishedSem queues currentSwapchain imageIndex
            
            case presentResult of
                Left ERROR_OUT_OF_DATE_KHR → do
                    logInfoM CatGraphics
                      "Swapchain out of date on present, recreating..."
                    recreateSwapchain window
                
                Left SUBOPTIMAL_KHR → do
                    logInfoM CatGraphics
                      "Swapchain suboptimal on present, recreating..."
                    recreateSwapchain window
                
                Left err → logAndThrowM CatGraphics
                  (ExGraphics SwapchainError) $ T.pack $
                    "Failed to present: " ⧺ show err
                
                Right () → pure ()
            
            -- Update frame index
            let nextFrame = (frameIdx + 1) `mod` fromIntegral (gcMaxFrames defaultGraphicsConfig)
            modify $ \s → s { graphicsState = (graphicsState s) {
                currentFrame = nextFrame } }
            
-- | Update uniform buffer for current frame
updateUniformBufferForFrame ∷ GLFW.Window → Word32 → Camera2D → EngineM ε σ ()
updateUniformBufferForFrame win frameIdx camera = do
    state ← gets graphicsState
    case (vulkanDevice state, uniformBuffers state) of
        (Just device, Just buffers) → do
            let (_, memory) = buffers V.! fromIntegral frameIdx
            (fbWidth, fbHeight) ← GLFW.getFramebufferSize win
            (winWidth, winHeight) ← GLFW.getWindowSize win

            env ← ask
            brightness ← liftIO $ readIORef (brightnessRef env)
            pixelSnap ← liftIO $ readIORef (pixelSnapRef env)
            sunAngle ← liftIO $ readIORef (sunAngleRef env)
            defFmSlot ← liftIO $ readIORef (defaultFaceMapSlotRef env)
            worldCirc ← liftIO $ activeWorldCircumferenceTiles env

            let ambientLight = computeAmbientLight sunAngle
            let uiCamera = UICamera (fromIntegral fbWidth) (fromIntegral fbHeight)
            let facingFloat = case camFacing camera of
                    FaceSouth → 0.0
                    FaceWest → 1.0
                    FaceNorth → 2.0
                    FaceEast → 3.0
            let uboData = UBO identity (createViewMatrix camera)
                              (createProjectionMatrix camera
                                  (fromIntegral fbWidth) (fromIntegral fbHeight))
                              (createUIViewMatrix uiCamera)
                              (createUIProjectionMatrix uiCamera)
                              (brightnessToMultiplier brightness)
                              -- Clamp to ≥1: the pixel-snap shader divides
                              -- by screenW/screenH, so a zero-size (minimize)
                              -- framebuffer would otherwise produce non-finite
                              -- vertex positions.
                              (fromIntegral (max 1 fbWidth))
                              (fromIntegral (max 1 fbHeight))
                              (if pixelSnap then 1.0 else 0.0)
                              sunAngle
                              ambientLight
                              facingFloat
                              (fromIntegral defFmSlot)
                              worldCirc

            liftIO $ writeIORef (windowSizeRef env) (winWidth, winHeight)
            liftIO $ writeIORef (framebufferSizeRef env) (fbWidth, fbHeight)
            
            updateUniformBuffer device memory uboData
        _ → logAndThrowM CatGraphics
          (ExGraphics VulkanDeviceLost) $
            T.pack "No device or uniform buffer"

-- | Submit frame to GPU
submitFrame ∷ CommandBuffer → FrameResources → DevQueues → Semaphore → EngineM ε σ ()
submitFrame cmdBuffer resources queues renderFinishedSem = do
    let waitStages = V.singleton PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT
        submitInfo = zero
            { waitSemaphores = V.singleton $ frImageAvailable resources
            , waitDstStageMask = waitStages
            , commandBuffers = V.singleton $ commandBufferHandle cmdBuffer
            , signalSemaphores = V.singleton renderFinishedSem
            }
    liftIO $ queueSubmit (graphicsQueue queues) 
               (V.singleton $ SomeStruct submitInfo) (frInFlight resources)

-- | Present frame and return result for handling
presentFrameWithResult ∷ Semaphore → DevQueues → SwapchainKHR → Word32
                       → EngineM ε σ (Either Result ())
presentFrameWithResult renderFinishedSem queues swapchain imageIndex = do
    let presentInfo = zero
            { waitSemaphores = V.singleton renderFinishedSem
            , swapchains = V.singleton swapchain
            , imageIndices = V.singleton imageIndex
            }
    presentResult ← liftIO $ queuePresentKHR (presentQueue queues) presentInfo
    case presentResult of
        SUCCESS               → pure $ Right ()
        SUBOPTIMAL_KHR        → pure $ Left SUBOPTIMAL_KHR
        ERROR_OUT_OF_DATE_KHR → pure $ Left ERROR_OUT_OF_DATE_KHR
        err                   → pure $ Left err

-- | Safe wrapper for acquireNextImageKHR
acquireNextImageKHRSafe ∷ Device → SwapchainKHR → Word64 → Semaphore → Fence 
                        → IO (Either Result Word32)
acquireNextImageKHRSafe device swapchain timeout semaphore fence = do
    (result, imageIndex) ← acquireNextImageKHR device swapchain timeout semaphore fence
    case result of
        SUCCESS               → pure $ Right imageIndex
        -- The image WAS acquired and the semaphore signaled — we must
        -- proceed and consume it (bailing out would reuse a still-
        -- signaled semaphore on the next acquire). The present-side
        -- SUBOPTIMAL result triggers the actual recreation.
        SUBOPTIMAL_KHR        → pure $ Right imageIndex
        ERROR_OUT_OF_DATE_KHR → pure $ Left ERROR_OUT_OF_DATE_KHR
        err                   → pure $ Left err
